// Este es el archivo datos-met.js
   const dbMet = [
    //ciclismo//
    { cod: "01003", met: 14.0, cat: "Ciclismo", act: "Ciclismo, de montaña, en ascenso, esfuerzo intenso" },
    { cod: "01004", met: 16.0, cat: "Ciclismo", act: "Ciclismo, de montaña, competitivo, carrera" },
    { cod: "01008", met: 8.5, cat: "Ciclismo", act: "Ciclismo, BMX" },
    { cod: "01009", met: 8.5, cat: "Ciclismo", act: "Ciclismo, de montaña, general" },
    { cod: "01010", met: 4.0, cat: "Ciclismo", act: "Ciclismo, <16 km/h, recreativo, al trabajo o por placer" },
    { cod: "01011", met: 6.8, cat: "Ciclismo", act: "Ciclismo, de/hacia el trabajo, a ritmo propio" },
    { cod: "01013", met: 5.8, cat: "Ciclismo", act: "Ciclismo, sobre camino de tierra o terreno agrícola, esfuerzo moderado" },
    { cod: "01015", met: 7.5, cat: "Ciclismo", act: "Ciclismo, general" },
    { cod: "01018", met: 3.5, cat: "Ciclismo", act: "Ciclismo, recreativo, 9 km/h" },
    { cod: "01019", met: 5.8, cat: "Ciclismo", act: "Ciclismo, recreativo, 15 km/h" },
    { cod: "01020", met: 6.8, cat: "Ciclismo", act: "Ciclismo, 16-19,2 km/h, recreativo, lento, esfuerzo ligero" },
    { cod: "01030", met: 8.0, cat: "Ciclismo", act: "Ciclismo, 19.3-22.4 km/h, recreativo, esfuerzo moderado" },
    { cod: "01040", met: 10.0, cat: "Ciclismo", act: "Ciclismo, 22.5-25.6 km/h, carrera o recreativo, rápido, esfuerzo intenso" },
    { cod: "01050", met: 12.0, cat: "Ciclismo", act: "Ciclismo, 25.7-30.6 km/h, muy rápido, carrera en general" },
    { cod: "01060", met: 15.8, cat: "Ciclismo", act: "Ciclismo, >32.2 km/h, carrera, sin ayuda aerodinámica" },
    { cod: "01065", met: 8.5, cat: "Ciclismo", act: "Ciclismo, 19.3 km/h, sentado, manos sobre el manubrio, 80 rpm" },
    { cod: "01066", met: 9.0, cat: "Ciclismo", act: "Ciclismo, 19.3 km/h, parado, manos sobre los frenos, 60 rpm" },
    { cod: "01070", met: 5.0, cat: "Ciclismo", act: "Uso de monociclo" },

    //ACONDICIONAMIENTO FISICO

    { cod: "02001", met: 2.3, cat: "Acondicionamiento Físico", act: "Video juegos (Wii Fit), esfuerzo ligero (equilibrio, yoga)" },
    { cod: "02003", met: 3.8, cat: "Acondicionamiento Físico", act: "Video juegos (Wii Fit), esfuerzo moderado (aerobic, fuerza)" },
    { cod: "02005", met: 7.2, cat: "Acondicionamiento Físico", act: "Video juegos (Exergaming, Dance Dance Revolution), intenso" },
    { cod: "02008", met: 5.0, cat: "Acondicionamiento Físico", act: "Ejercicio con obstáculos de tipo militar, entrenamiento de campo" },
    { cod: "02010", met: 7.0, cat: "Acondicionamiento Físico", act: "Ciclismo, bicicleta fija, general" },
    { cod: "02011", met: 3.5, cat: "Acondicionamiento Físico", act: "Ciclismo, bicicleta fija, 30-50 watts, muy ligero" },
    { cod: "02012", met: 6.8, cat: "Acondicionamiento Físico", act: "Ciclismo, bicicleta fija, 90-100 watts, moderado a intenso" },
    { cod: "02013", met: 8.8, cat: "Acondicionamiento Físico", act: "Ciclismo, bicicleta fija, 101-160 watts, intenso" },
    { cod: "02014", met: 11.0, cat: "Acondicionamiento Físico", act: "Ciclismo, bicicleta fija, 161-200 watts, intenso" },
    { cod: "02015", met: 14.0, cat: "Acondicionamiento Físico", act: "Ciclismo, bicicleta fija, 201-270 watts, muy intenso" },
    { cod: "02017", met: 4.8, cat: "Acondicionamiento Físico", act: "Ciclismo, bicicleta fija, 51-89 watts, ligero a moderado" },
    { cod: "02019", met: 8.5, cat: "Acondicionamiento Físico", act: "Ciclismo, bicicleta fija, RPM/Spinning" },
    { cod: "02020", met: 8.0, cat: "Acondicionamiento Físico", act: "Calistenia (flexiones, abdominales, dominadas), intenso" },
    { cod: "02022", met: 3.8, cat: "Acondicionamiento Físico", act: "Calistenia (flexiones, abdominales, estocadas), moderado" },
    { cod: "02024", met: 2.8, cat: "Acondicionamiento Físico", act: "Calistenia (abdominales crunch, sit up), ligero" },
    { cod: "02030", met: 3.5, cat: "Acondicionamiento Físico", act: "Calistenia, ligero o moderado, general" },
    { cod: "02035", met: 4.3, cat: "Acondicionamiento Físico", act: "Entrenamiento en circuito, esfuerzo moderado" },
    { cod: "02040", met: 8.0, cat: "Acondicionamiento Físico", act: "Entrenamiento en circuito, pesas Rusas (kettlebells), intenso" },
    { cod: "02045", met: 3.5, cat: "Acondicionamiento Físico", act: "Rutinas de entrenamiento CurvesTM para mujeres" },
    { cod: "02048", met: 5.0, cat: "Acondicionamiento Físico", act: "Entrenamiento en elíptico, esfuerzo moderado" },
    { cod: "02050", met: 6.0, cat: "Acondicionamiento Físico", act: "Entrenamiento de fuerza (levantamiento pesas, máquinas), intenso" },
    { cod: "02052", met: 5.0, cat: "Acondicionamiento Físico", act: "Entrenamiento de fuerza (con pesas), sentadillas" },
    { cod: "02054", met: 3.5, cat: "Acondicionamiento Físico", act: "Entrenamiento de fuerza, 8-15 reps con resistencia variable" },
    { cod: "02060", met: 5.5, cat: "Acondicionamiento Físico", act: "Actividad física en centros de salud, general" },
    { cod: "02061", met: 5.0, cat: "Acondicionamiento Físico", act: "Gimnasia/pesas en una sesión, centros de salud" },
    { cod: "02062", met: 7.8, cat: "Acondicionamiento Físico", act: "Clases de acondicionamiento físico, centros de salud" },
    { cod: "02064", met: 3.8, cat: "Acondicionamiento Físico", act: "Ejercicios en el hogar, general" },
    { cod: "02065", met: 9.0, cat: "Acondicionamiento Físico", act: "Ergómetro escalador, general" },
    { cod: "02068", met: 12.3, cat: "Acondicionamiento Físico", act: "Salto con soga, general" },
    { cod: "02070", met: 6.0, cat: "Acondicionamiento Físico", act: "Remo, fijo en ergómetro, intenso" },
    { cod: "02071", met: 4.8, cat: "Acondicionamiento Físico", act: "Remo, fijo, general, moderado" },
    { cod: "02072", met: 7.0, cat: "Acondicionamiento Físico", act: "Remo, fijo, 100 watts, moderado" },
    { cod: "02073", met: 8.5, cat: "Acondicionamiento Físico", act: "Remo, fijo, 150 watts, intenso" },
    { cod: "02074", met: 12.0, cat: "Acondicionamiento Físico", act: "Remo, fijo, 200 watts, muy intenso" },
    { cod: "02080", met: 6.8, cat: "Acondicionamiento Físico", act: "Máquina simuladora de ski, general" },
    { cod: "02085", met: 11.0, cat: "Acondicionamiento Físico", act: "Plataforma de deslizamiento lateral, general" },
    { cod: "02090", met: 6.0, cat: "Acondicionamiento Físico", act: "Gimnasia reductora/modeladora, baile coreográfico" },
    { cod: "02101", met: 2.3, cat: "Acondicionamiento Físico", act: "Estiramientos, suave" },
    { cod: "02105", met: 3.0, cat: "Acondicionamiento Físico", act: "Pilates, general" },
    { cod: "02110", met: 6.8, cat: "Acondicionamiento Físico", act: "Dictado de clases (ej: aerobic, natación)" },
    { cod: "02112", met: 2.8, cat: "Acondicionamiento Físico", act: "Ejercicios terapéuticos con pelota, fitball" },
    { cod: "02115", met: 2.8, cat: "Acondicionamiento Físico", act: "Ejercicios con miembros superiores, ergómetro de brazos" },
    { cod: "02117", met: 4.3, cat: "Acondicionamiento Físico", act: "Bicicleta fija Airdyne (brazos solamente), moderado" },
    { cod: "02120", met: 5.3, cat: "Acondicionamiento Físico", act: "Aquaerobic, calistenia acuática" },
    { cod: "02135", met: 1.3, cat: "Acondicionamiento Físico", act: "Uso de hidromasaje, sentado" },
    { cod: "02140", met: 2.3, cat: "Acondicionamiento Físico", act: "Ejercicios por video TV (yoga, elongación), ligero" },
    { cod: "02143", met: 4.0, cat: "Acondicionamiento Físico", act: "Ejercicios por video TV (fuerza-resistencia), moderado" },
    { cod: "02146", met: 6.0, cat: "Acondicionamiento Físico", act: "Ejercicios por video TV (fuerza-resistencia), intenso" },
    { cod: "02150", met: 2.5, cat: "Acondicionamiento Físico", act: "Yoga, Hatha" },
    { cod: "02160", met: 4.0, cat: "Acondicionamiento Físico", act: "Yoga, power yoga" },
    { cod: "02170", met: 2.0, cat: "Acondicionamiento Físico", act: "Yoga, Nadi Sodhana" },
    { cod: "02180", met: 3.3, cat: "Acondicionamiento Físico", act: "Yoga, Surya Namaskar" },
    { cod: "02200", met: 5.3, cat: "Acondicionamiento Físico", act: "Ejercicios Neozelandeses (Haka, Waita Tira), moderado" },
    { cod: "02205", met: 6.8, cat: "Acondicionamiento Físico", act: "Ejercicios Neozelandeses (Haka, Taiahab), intenso" },

    // DANZA/BAILE
    { cod: "03010", met: 5.0, cat: "Danza/Baile", act: "Ballet, moderno o jazz, clases o ensayo" },
    { cod: "03012", met: 6.8, cat: "Danza/Baile", act: "Ballet, moderno o jazz, presentación, intenso" },
    { cod: "03014", met: 4.8, cat: "Danza/Baile", act: "Tap" },
    { cod: "03015", met: 7.3, cat: "Danza/Baile", act: "Aerobic, general" },
    { cod: "03016", met: 7.5, cat: "Danza/Baile", act: "Aerobic, step (15-20 cm)" },
    { cod: "03017", met: 9.5, cat: "Danza/Baile", act: "Aerobic, step (25-30 cm)" },
    { cod: "03018", met: 5.5, cat: "Danza/Baile", act: "Aerobic, step (10 cm)" },
    { cod: "03019", met: 8.5, cat: "Danza/Baile", act: "Clases de step, general" },
    { cod: "03020", met: 5.0, cat: "Danza/Baile", act: "Aerobic, bajo impacto" },
    { cod: "03021", met: 7.3, cat: "Danza/Baile", act: "Aerobic, alto impacto" },
    { cod: "03022", met: 10.0, cat: "Danza/Baile", act: "Aerobic dance utilizando 4.5-7 kg" },
    { cod: "03025", met: 4.5, cat: "Danza/Baile", act: "Danzas étnicas (Salsa, Merengue, Flamenco, etc.)" },
    { cod: "03030", met: 5.5, cat: "Danza/Baile", act: "Baile de salón, rápido" },
    { cod: "03031", met: 7.8, cat: "Danza/Baile", act: "Danza general (Disco, Folklore, Country, etc.)" },
    { cod: "03038", met: 11.3, cat: "Danza/Baile", act: "Baile de salón, competitivo" },
    { cod: "03040", met: 3.0, cat: "Danza/Baile", act: "Baile de salón, lento (Vals, Tango, Samba, etc.)" },
    { cod: "03050", met: 5.5, cat: "Danza/Baile", act: "Danza Anishinaabe" },
    { cod: "03060", met: 3.5, cat: "Danza/Baile", act: "Danza Caribeana (Bongo, Ibo, Jonkonnu, etc.)" },

    //CAZA Y PESCA

    { cod: "04001", met: 3.5, cat: "Caza y Pesca", act: "Pesca, general" },
    { cod: "04005", met: 4.5, cat: "Caza y Pesca", act: "Pesca, pesca de cangrejo" },
    { cod: "04007", met: 4.0, cat: "Caza y Pesca", act: "Pesca, caza manual" },
    { cod: "04010", met: 4.3, cat: "Caza y Pesca", act: "Búsqueda de lombrices con pala" },
    { cod: "04020", met: 4.0, cat: "Caza y Pesca", act: "Pesca costera y caminando" },
    { cod: "04030", met: 2.0, cat: "Caza y Pesca", act: "Pesca desde bote o canoa, sentado" },
    { cod: "04040", met: 3.5, cat: "Caza y Pesca", act: "Pesca costera, de pie" },
    { cod: "04050", met: 6.0, cat: "Caza y Pesca", act: "Pesca en arroyo, usando waders" },
    { cod: "04060", met: 2.0, cat: "Caza y Pesca", act: "Pesca en hielo, sentado" },
    { cod: "04061", met: 1.8, cat: "Caza y Pesca", act: "Pesca con mosca o línea, de pie" },
    { cod: "04062", met: 3.5, cat: "Caza y Pesca", act: "Pesca con red hundida, general" },
    { cod: "04063", met: 3.8, cat: "Caza y Pesca", act: "Pesca con red fija, instalar y recoger" },
    { cod: "04064", met: 3.0, cat: "Caza y Pesca", act: "Pesca con reel, instalar y recoger" },
    { cod: "04065", met: 2.3, cat: "Caza y Pesca", act: "Pesca con arpón, de pie" },
    { cod: "04070", met: 2.5, cat: "Caza y Pesca", act: "Caza, arco y flecha o ballesta" },
    { cod: "04080", met: 6.0, cat: "Caza y Pesca", act: "Caza mayor (ciervo, alce)" },
    { cod: "04081", met: 11.3, cat: "Caza y Pesca", act: "Caza mayor, transporte de la presa" },
    { cod: "04083", met: 4.0, cat: "Caza y Pesca", act: "Caza de animales marinos grandes" },
    { cod: "04085", met: 2.5, cat: "Caza y Pesca", act: "Caza mayor, de pie, movimientos limitados" },
    { cod: "04086", met: 2.0, cat: "Caza y Pesca", act: "Caza mayor desde auto, avión o bote" },
    { cod: "04090", met: 2.5, cat: "Caza y Pesca", act: "Caza, patos, aves" },
    { cod: "04095", met: 3.0, cat: "Caza y Pesca", act: "Caza de murciélagos o ardillas" },
    { cod: "04110", met: 6.0, cat: "Caza y Pesca", act: "Caza, faisán o gallo" },
    { cod: "04115", met: 3.3, cat: "Caza y Pesca", act: "Caza, pájaros" },
    { cod: "04120", met: 5.0, cat: "Caza y Pesca", act: "Caza menor (conejos, ardillas, mapache)" },
    { cod: "04123", met: 3.3, cat: "Caza y Pesca", act: "Caza, puerco salvaje" },
    { cod: "04124", met: 2.0, cat: "Caza y Pesca", act: "Juegos de captura, general" },
    { cod: "04125", met: 9.5, cat: "Caza y Pesca", act: "Caza, en excursión con equipo pesado" },
    { cod: "04130", met: 2.5, cat: "Caza y Pesca", act: "Tiro con pistola o al plato, de pie" },
    { cod: "04140", met: 2.3, cat: "Caza y Pesca", act: "Tiro con rifle, acostado" },
    { cod: "04145", met: 2.5, cat: "Caza y Pesca", act: "Tiro con rifle, de rodillas o de pie" },

//ACTIVIDADES DOMESTICAS
    { cod: "05010", met: 3.3, cat: "Actividades Domésticas", act: "Limpieza, barrido de alfombra o suelo, general" },
    { cod: "05011", met: 2.3, cat: "Actividades Domésticas", act: "Limpieza, barrido, lento, esfuerzo ligero" },
    { cod: "05012", met: 3.8, cat: "Actividades Domésticas", act: "Limpieza, barrido, lento, esfuerzo moderado" },
    { cod: "05020", met: 3.5, cat: "Actividades Domésticas", act: "Limpieza, intensa o profunda (ej: limpieza de auto, vidrios, garage), esfuerzo moderado" },
    { cod: "05021", met: 3.5, cat: "Actividades Domésticas", act: "Limpieza, trapeando, de pie, esfuerzo moderado" },
    { cod: "05022", met: 3.2, cat: "Actividades Domésticas", act: "Limpieza y lavado de vidrios y ventanas, general" },
    { cod: "05023", met: 2.5, cat: "Actividades Domésticas", act: "Trapeo, de pie, esfuerzo ligero" },
    { cod: "05024", met: 4.5, cat: "Actividades Domésticas", act: "Encerado de pisos, de pie, caminando lento, usando enceradora eléctrica" },
    { cod: "05025", met: 2.8, cat: "Actividades Domésticas", act: "Tareas domésticas múltiples en simultáneo, esfuerzo ligero" },
    { cod: "05026", met: 3.5, cat: "Actividades Domésticas", act: "Tareas domésticas múltiples en simultáneo, esfuerzo moderado" },
    { cod: "05027", met: 4.3, cat: "Actividades Domésticas", act: "Tareas domésticas múltiples en simultáneo, esfuerzo intenso" },
    { cod: "05030", met: 3.3, cat: "Actividades Domésticas", act: "Limpieza, caza o cabaña, general, esfuerzo moderado" },
    { cod: "05032", met: 2.3, cat: "Actividades Domésticas", act: "Sacudir o lustrar muebles, general" },
    { cod: "05035", met: 3.3, cat: "Actividades Domésticas", act: "Actividades de cocina, general (ej: cocinar, lavar los platos, limpiar), esfuerzo moderado" },
    { cod: "05040", met: 2.5, cat: "Actividades Domésticas", act: "Limpieza, general (acomodar, cambiar las sábanas, sacar la basura), esfuerzo ligero" },
    { cod: "05041", met: 1.8, cat: "Actividades Domésticas", act: "Lavado de platos, de pie o en general (sin interrupción)" },
    { cod: "05042", met: 2.5, cat: "Actividades Domésticas", act: "Lavado de platos, recoger los platos de la mesa, caminando, esfuerzo ligero" },
    { cod: "05043", met: 3.3, cat: "Actividades Domésticas", act: "Aspirar, general, esfuerzo moderado" },
    { cod: "05044", met: 3.0, cat: "Actividades Domésticas", act: "Matar animales para preparación de alimentos, pequeños" },
    { cod: "05045", met: 6.0, cat: "Actividades Domésticas", act: "Matar animales para preparación de alimentos, grandes, esfuerzo intenso" },
    { cod: "05046", met: 2.3, cat: "Actividades Domésticas", act: "Cortar y ahumar pescado, secar pescado o carne" },
    { cod: "05048", met: 4.0, cat: "Actividades Domésticas", act: "Curtido de pieles, general" },
    { cod: "05049", met: 3.5, cat: "Actividades Domésticas", act: "Cocción o preparación de alimentos, esfuerzo moderado" },
    { cod: "05050", met: 2.0, cat: "Actividades Domésticas", act: "Cocción o preparación de alimentos, de pie/sentado, utensilios manuales, ligero" },
    { cod: "05051", met: 2.5, cat: "Actividades Domésticas", act: "Servir los alimentos, preparar la mesa, con desplazamiento o de pie" },
    { cod: "05052", met: 2.5, cat: "Actividades Domésticas", act: "Cocción o preparación de alimentos, con desplazamiento" },
    { cod: "05053", met: 2.5, cat: "Actividades Domésticas", act: "Alimentar animales domésticos" },
    { cod: "05055", met: 2.5, cat: "Actividades Domésticas", act: "Movilización de productos alimenticios, transporte de paquetes" },
    { cod: "05056", met: 7.5, cat: "Actividades Domésticas", act: "Transporte de alimentos subiendo escaleras" },
    { cod: "05057", met: 3.0, cat: "Actividades Domésticas", act: "Cocinar Pan Indú en horno exterior" },
    { cod: "05060", met: 2.3, cat: "Actividades Domésticas", act: "Compra de alimentos con o sin carro de compras, de pie o caminando" },
    { cod: "05065", met: 2.3, cat: "Actividades Domésticas", act: "Compras (no alimentos), con o sin carro, de pie o caminando" },
    { cod: "05070", met: 1.8, cat: "Actividades Domésticas", act: "Planchado de ropa" },
    { cod: "05080", met: 1.3, cat: "Actividades Domésticas", act: "Tejido, costura, esfuerzo ligero, envoltura de regalos, sentado" },
    { cod: "05082", met: 2.8, cat: "Actividades Domésticas", act: "Costura a máquina" },
    { cod: "05090", met: 2.0, cat: "Actividades Domésticas", act: "Lavado de ropa, doblar/colgar, poner lavadora, a mano, ligero" },
    { cod: "05092", met: 4.0, cat: "Actividades Domésticas", act: "Lavado de ropa, tendido de ropa, lavado a mano, esfuerzo moderado" },
    { cod: "05095", met: 2.3, cat: "Actividades Domésticas", act: "Lavado de ropa, acomodar ropa, guardar ropa limpia, con desplazamiento" },
    { cod: "05100", met: 3.3, cat: "Actividades Domésticas", act: "Tender la cama, cambiar las sábanas" },
    { cod: "05110", met: 5.0, cat: "Actividades Domésticas", act: "Recolección y producción de jarabe de arce (transporte cubetas/madera)" },
    { cod: "05120", met: 5.8, cat: "Actividades Domésticas", act: "Movilización de muebles, artículos del hogar, cajas" },
    { cod: "05121", met: 5.0, cat: "Actividades Domésticas", act: "Mudanza, movilización de cargas ligeras" },
    { cod: "05125", met: 4.8, cat: "Actividades Domésticas", act: "Ordenar la habitación" },
    { cod: "05130", met: 3.5, cat: "Actividades Domésticas", act: "Limpieza de pisos (manos y rodillas), baño, bañera, moderado" },
    { cod: "05131", met: 2.0, cat: "Actividades Domésticas", act: "Limpieza de pisos (manos y rodillas), baño, bañera, ligero" },
    { cod: "05132", met: 6.5, cat: "Actividades Domésticas", act: "Limpieza de pisos (manos y rodillas), baño, bañera, intenso" },
    { cod: "05140", met: 4.0, cat: "Actividades Domésticas", act: "Barrido de garage, acera o los exteriores de la casa" },
    { cod: "05146", met: 3.5, cat: "Actividades Domésticas", act: "Armar/desarmar cajas, movilización liviana, carga/descarga auto" },
    { cod: "05147", met: 3.0, cat: "Actividades Domésticas", act: "En movimiento, movilización de productos del hogar, esfuerzo moderado" },
    { cod: "05148", met: 2.5, cat: "Actividades Domésticas", act: "Regado las plantas" },
    { cod: "05149", met: 2.5, cat: "Actividades Domésticas", act: "Encendido de chimenea" },
    { cod: "05150", met: 9.0, cat: "Actividades Domésticas", act: "Movilización de productos del hogar subiendo escaleras (cajas/muebles)" },
    { cod: "05160", met: 2.0, cat: "Actividades Domésticas", act: "De pie, tareas de esfuerzo ligero (cargar combustible, foco luz, etc)" },
    { cod: "05165", met: 3.5, cat: "Actividades Domésticas", act: "En movimiento, tareas moderadas (prepararse salir, cerrar ventanas, etc)" },
    { cod: "05170", met: 2.2, cat: "Actividades Domésticas", act: "Sentado, juego con niños, esfuerzo ligero (períodos activos)" },
    { cod: "05171", met: 2.8, cat: "Actividades Domésticas", act: "De pie, juego con niños, esfuerzo ligero (períodos activos)" },
    { cod: "05175", met: 3.5, cat: "Actividades Domésticas", act: "Caminando/corriendo, juego con niños, esfuerzo moderado" },
    { cod: "05180", met: 5.8, cat: "Actividades Domésticas", act: "Caminando/corriendo, juego con niños, esfuerzo intenso" },
    { cod: "05181", met: 3.0, cat: "Actividades Domésticas", act: "Caminar y llevar niños pequeños (7 kg o más)" },
    { cod: "05182", met: 2.3, cat: "Actividades Domésticas", act: "Caminar y llevar niños pequeños (menos de 7 kg)" },
    { cod: "05183", met: 2.0, cat: "Actividades Domésticas", act: "De pie, cargando un niño" },
    { cod: "05184", met: 2.5, cat: "Actividades Domésticas", act: "Cuidado de niños, bebés, general" },
    { cod: "05185", met: 2.0, cat: "Actividades Domésticas", act: "Cuidado niños, sentado/rodillas (vestir, bañar, alimentar), ligero" },
    { cod: "05186", met: 3.0, cat: "Actividades Domésticas", act: "Cuidado niños, de pie (vestir, bañar, alimentar), moderado" },
    { cod: "05188", met: 1.5, cat: "Actividades Domésticas", act: "Reclinarse con el bebé" },
    { cod: "05189", met: 2.0, cat: "Actividades Domésticas", act: "Amamantar al bebé, sentada o reclinada" },
    { cod: "05190", met: 2.5, cat: "Actividades Domésticas", act: "Sentado, jugar con animales, esfuerzo ligero (períodos activos)" },
    { cod: "05191", met: 2.8, cat: "Actividades Domésticas", act: "De pie, jugar con animales, esfuerzo ligero (períodos activos)" },
    { cod: "05192", met: 3.0, cat: "Actividades Domésticas", act: "Caminar/correr, jugar con animales, general, esfuerzo ligero" },
    { cod: "05193", met: 4.0, cat: "Actividades Domésticas", act: "Caminar/correr, jugar con animales, esfuerzo moderado" },
    { cod: "05194", met: 5.0, cat: "Actividades Domésticas", act: "Caminar/correr, jugar con animales, esfuerzo intenso" },
    { cod: "05195", met: 3.5, cat: "Actividades Domésticas", act: "De pie, bañar al perro" },
    { cod: "05197", met: 2.3, cat: "Actividades Domésticas", act: "Cuidado de animales, animales domésticos, general" },
    { cod: "05200", met: 4.0, cat: "Actividades Domésticas", act: "Cuidado de mayores/discapacidad, aseo, vestimenta, traslado" },
    { cod: "05205", met: 2.3, cat: "Actividades Domésticas", act: "Cuidado de mayores/discapacidad, alimentación, cepillado, ligero" },


// REPARACIONES DOMESTICAS

    { cod: "06020", met: 4.0, cat: "Reparaciones Domésticas", act: "Mantención de la carrocería automotríz" },
    { cod: "06030", met: 3.3, cat: "Reparaciones Domésticas", act: "Reparación automotríz, esfuerzo ligero o moderado" },
    { cod: "06040", met: 3.0, cat: "Reparaciones Domésticas", act: "Carpintería, general, taller" },
    { cod: "06050", met: 6.0, cat: "Reparaciones Domésticas", act: "Carpintería, exterior de la casa, instalación de canaletas de desague" },
    { cod: "06052", met: 3.8, cat: "Reparaciones Domésticas", act: "Carpintería, exterior de la casa, construcción de cercas" },
    { cod: "06060", met: 3.3, cat: "Reparaciones Domésticas", act: "Carpintería, finalización o restauración de armarios o muebles" },
    { cod: "06070", met: 6.0, cat: "Reparaciones Domésticas", act: "Carpintería, serruchado de madera" },
    { cod: "06072", met: 4.0, cat: "Reparaciones Domésticas", act: "Carpintería, tareas de remodelación del hogar, esfuerzo moderado" },
    { cod: "06074", met: 2.3, cat: "Reparaciones Domésticas", act: "Carpintería, tareas de remodelación del hogar, esfuerzo ligero" },
    { cod: "06080", met: 5.0, cat: "Reparaciones Domésticas", act: "Masillado, grietas en madera" },
    { cod: "06090", met: 4.5, cat: "Reparaciones Domésticas", act: "Masillado, exceptuando grietas en madera" },
    { cod: "06100", met: 5.0, cat: "Reparaciones Domésticas", act: "Limpieza de desagues" },
    { cod: "06110", met: 5.0, cat: "Reparaciones Domésticas", act: "Excavación para construcción de garage" },
    { cod: "06120", met: 5.0, cat: "Reparaciones Domésticas", act: "Colocación de ventanas anti tormentas" },
    { cod: "06122", met: 5.0, cat: "Reparaciones Domésticas", act: "Colgar paneles de yeso en el interior del hogar" },
    { cod: "06124", met: 3.0, cat: "Reparaciones Domésticas", act: "Martillar clavos" },
    { cod: "06126", met: 2.5, cat: "Reparaciones Domésticas", act: "Reparaciones domésticas, general, esfuerzo ligero" },
    { cod: "06127", met: 4.5, cat: "Reparaciones Domésticas", act: "Reparaciones domésticas, general, esfuerzo moderado" },
    { cod: "06128", met: 6.0, cat: "Reparaciones Domésticas", act: "Reparaciones domésticas, general, esfuerzo intenso" },
    { cod: "06130", met: 4.5, cat: "Reparaciones Domésticas", act: "Colocar o quitar alfombras" },
    { cod: "06140", met: 3.8, cat: "Reparaciones Domésticas", act: "Colocar azulejos o linóleo, reparación de electrodomésticos" },
    { cod: "06144", met: 3.0, cat: "Reparaciones Domésticas", act: "Reparación de electrodomésticos" },
    { cod: "06150", met: 5.0, cat: "Reparaciones Domésticas", act: "Pintura, en el exterior del hogar" },
    { cod: "06160", met: 3.3, cat: "Reparaciones Domésticas", act: "Pintura, en el interior del hogar, empapelado, quitar pintura" },
    { cod: "06165", met: 4.5, cat: "Reparaciones Domésticas", act: "Pintura, general" },
    { cod: "06167", met: 3.0, cat: "Reparaciones Domésticas", act: "Plomeria, general" },
    { cod: "06170", met: 3.0, cat: "Reparaciones Domésticas", act: "Colocar y quitar la lona cobertora de un velero" },
    { cod: "06180", met: 6.0, cat: "Reparaciones Domésticas", act: "Techado" },
    { cod: "06190", met: 4.5, cat: "Reparaciones Domésticas", act: "Pulir pisos con puidora eléctrica" },
    { cod: "06200", met: 4.5, cat: "Reparaciones Domésticas", act: "Despintar y pintar veleros o lanchas de motor" },
    { cod: "06205", met: 2.0, cat: "Reparaciones Domésticas", act: "Afilado de herramientas" },
    { cod: "06210", met: 5.0, cat: "Reparaciones Domésticas", act: "Esparcir tierra con pala" },
    { cod: "06220", met: 4.5, cat: "Reparaciones Domésticas", act: "Lavado y encerado externo de veleros o aviónes" },
    { cod: "06225", met: 2.0, cat: "Reparaciones Domésticas", act: "Lavado y encerado de autos" },
    { cod: "06230", met: 4.5, cat: "Reparaciones Domésticas", act: "Lavado de cercos, pintura de cercos, esfuerzo moderado" },
    { cod: "06240", met: 3.3, cat: "Reparaciones Domésticas", act: "Cableado, instalación eléctrica" },


    //INACTIVIDAD
    { cod: "07010", met: 1.0, cat: "Inactividad", act: "Descansar en silencio y mirar televisión" },
    { cod: "07011", met: 1.3, cat: "Inactividad", act: "Descansar en silencio, despierto sobre la cama, escuchando música" },
    { cod: "07020", met: 1.3, cat: "Inactividad", act: "Mirar televisión, sentado en silencio" },
    { cod: "07021", met: 1.3, cat: "Inactividad", act: "Sentado, en silencio, general" },
    { cod: "07022", met: 1.5, cat: "Inactividad", act: "Sentado en silencio, algunos movimientos, moviendo las manos" },
    { cod: "07023", met: 1.8, cat: "Inactividad", act: "Sentado, moviendo los pies" },
    { cod: "07024", met: 1.3, cat: "Inactividad", act: "Sentado, fumando" },
    { cod: "07025", met: 1.5, cat: "Inactividad", act: "Sentado, escuchando música (sin hablar o leer)" },
    { cod: "07026", met: 1.3, cat: "Inactividad", act: "Sentado en el escritorio, apoyando la cabeza sobre las manos" },
    { cod: "07030", met: 0.95, cat: "Inactividad", act: "Dormir" },
    { cod: "07040", met: 1.3, cat: "Inactividad", act: "De pie en silencio, esperando en una hilera" },
    { cod: "07041", met: 1.8, cat: "Inactividad", act: "De pie, realizando algunos movimientos" },
    { cod: "07050", met: 1.3, cat: "Inactividad", act: "Recostado, escribiendo" },
    { cod: "07060", met: 1.3, cat: "Inactividad", act: "Recostado, conversando o hablando por teléfono" },
    { cod: "07070", met: 1.3, cat: "Inactividad", act: "Recostado, leyendo" },
    { cod: "07075", met: 1.0, cat: "Inactividad", act: "Meditación" },

//CESPED Y JARDIN
{ cod: "08009", met: 3.3, cat: "Césped y Jardín", act: "Transporte, carga o apilamiento de madera, esfuerzo ligero a moderado" },
    { cod: "08010", met: 5.5, cat: "Césped y Jardín", act: "Transporte, carga o apilamiento de madera, carga/descarga" },
    { cod: "08019", met: 4.5, cat: "Césped y Jardín", act: "Corte de madera, tala de troncos, esfuerzo moderado" },
    { cod: "08020", met: 6.3, cat: "Césped y Jardín", act: "Corte de madera, tala de troncos, esfuerzo intenso" },
    { cod: "08025", met: 3.5, cat: "Césped y Jardín", act: "Recorte de arbustos pequeños, recorte de césped, esfuerzo moderado" },
    { cod: "08030", met: 6.3, cat: "Césped y Jardín", act: "Arreglo de arbustos/terreno, trabajo de la tierra, carretilla, intenso" },
    { cod: "08040", met: 5.0, cat: "Césped y Jardín", act: "Excavar un arenero, usando pala" },
    { cod: "08045", met: 3.5, cat: "Césped y Jardín", act: "Excavar, uso de pala, relleno del jardín, abono, ligero a moderado" },
    { cod: "08050", met: 5.0, cat: "Césped y Jardín", act: "Excavar, uso de pala, relleno del jardín, abono de tierra" },
    { cod: "08052", met: 7.8, cat: "Césped y Jardín", act: "Excavar, uso de pala, relleno del jardín, abono, esfuerzo intenso" },
    { cod: "08055", met: 2.8, cat: "Césped y Jardín", act: "Conducir un tractor" },
    { cod: "08057", met: 8.3, cat: "Césped y Jardín", act: "Talado de árboles, gran tamaño" },
    { cod: "08058", met: 5.3, cat: "Césped y Jardín", act: "Talado de árboles, tamaño pequeño a mediano" },
    { cod: "08060", met: 5.8, cat: "Césped y Jardín", act: "Jardinería con herramientas eléctricas pesadas, motosierra" },
    { cod: "08065", met: 2.3, cat: "Césped y Jardín", act: "Jardinería, uso de containers, personas mayores de 60 años" },
    { cod: "08070", met: 4.0, cat: "Césped y Jardín", act: "Canales de riego, apertura y cierre de puertos" },
    { cod: "08080", met: 6.3, cat: "Césped y Jardín", act: "Colocación de piedras pequeñas para jardín" },
    { cod: "08090", met: 5.0, cat: "Césped y Jardín", act: "Colocación de césped" },
    { cod: "08095", met: 5.5, cat: "Césped y Jardín", act: "Corte de césped, general" },
    { cod: "08100", met: 2.5, cat: "Césped y Jardín", act: "Corte de césped, conducir una cortadora de césped" },
    { cod: "08110", met: 6.0, cat: "Césped y Jardín", act: "Corte de césped, caminando, con cortadora manual" },
    { cod: "08120", met: 5.0, cat: "Césped y Jardín", act: "Corte de césped, caminando, con cortadora eléctrica, moderado/vigoroso" },
    { cod: "08125", met: 4.5, cat: "Césped y Jardín", act: "Corte de césped, con cortadora eléctrica, esfuerzo ligero o moderado" },
    { cod: "08130", met: 2.5, cat: "Césped y Jardín", act: "Uso de máquina quitanieve, caminando" },
    { cod: "08135", met: 2.0, cat: "Césped y Jardín", act: "Plantar, abono de tierra, plantación de semillas o plantas, ligero" },
    { cod: "08140", met: 4.3, cat: "Césped y Jardín", act: "Plantación de semillas, arbustos, agachado, esfuerzo moderado" },
    { cod: "08145", met: 4.3, cat: "Césped y Jardín", act: "Plantación de frutas, vegetales o plantas, agachado, moderado" },
    { cod: "08150", met: 4.5, cat: "Césped y Jardín", act: "Plantación de árboles" },
    { cod: "08160", met: 3.8, cat: "Césped y Jardín", act: "Rastrillado de hojas o césped, esfuerzo moderado" },
    { cod: "08165", met: 4.0, cat: "Césped y Jardín", act: "Rastrillado de césped" },
    { cod: "08170", met: 4.0, cat: "Césped y Jardín", act: "Rastrillado de techo con rastrillo de nieve" },
    { cod: "08180", met: 3.0, cat: "Césped y Jardín", act: "Conducción de máquina quitanieve" },
    { cod: "08190", met: 4.0, cat: "Césped y Jardín", act: "Embolsado de césped, hojas" },
    { cod: "08192", met: 5.5, cat: "Césped y Jardín", act: "Uso de la pala en lodo o suciedad" },
    { cod: "08195", met: 5.3, cat: "Césped y Jardín", act: "Uso de la pala en nieve, a mano, esfuerzo moderado" },
    { cod: "08200", met: 6.0, cat: "Césped y Jardín", act: "Uso de la pala en nieve, a mano" },
    { cod: "08202", met: 7.5, cat: "Césped y Jardín", act: "Uso de la pala en nieve, a mano, esfuerzo intenso" },
    { cod: "08210", met: 4.0, cat: "Césped y Jardín", act: "Recorte de arbustos o árboles, corte manual" },
    { cod: "08215", met: 3.5, cat: "Césped y Jardín", act: "Recorte de arbustos/árboles, cortadora eléctrica, sopladores, bordeadoras" },
    { cod: "08220", met: 3.0, cat: "Césped y Jardín", act: "Caminando, aplicación de fertilizante o sembrado, aplicador a presión" },
    { cod: "08230", met: 1.5, cat: "Césped y Jardín", act: "Riego de césped o jardín, de pie o caminando" },
    { cod: "08239", met: 3.5, cat: "Césped y Jardín", act: "Desmalezado, cultivo del jardín, esfuerzo ligero a moderado" },
    { cod: "08240", met: 4.5, cat: "Césped y Jardín", act: "Desmalezado, cultivo del jardín" },
    { cod: "08241", met: 5.0, cat: "Césped y Jardín", act: "Desmalezado, cultivo del jardín, uso de la azada, moderado a intenso" },
    { cod: "08245", met: 3.8, cat: "Césped y Jardín", act: "Jardinería, general, esfuerzo moderado" },
    { cod: "08246", met: 3.5, cat: "Césped y Jardín", act: "Recolección de frutas de árboles, recolección vegetales, moderado" },
    { cod: "08248", met: 4.5, cat: "Césped y Jardín", act: "Recolección de frutas, uso de escalera, esfuerzo intenso" },
    { cod: "08250", met: 3.3, cat: "Césped y Jardín", act: "Cuidado del jardín, ligero, recolección flores, caminando/de pie" },
    { cod: "08251", met: 3.0, cat: "Césped y Jardín", act: "Recolección de herramientas de jardinería, caminando" },
    { cod: "08255", met: 5.5, cat: "Césped y Jardín", act: "Empuje de carro de jardinería o carretilla" },
    { cod: "08260", met: 3.0, cat: "Césped y Jardín", act: "Jardinería, general, esfuerzo ligero" },
    { cod: "08261", met: 4.0, cat: "Césped y Jardín", act: "Jardinería, general, esfuerzo moderado" },
    { cod: "08262", met: 6.0, cat: "Césped y Jardín", act: "Jardinería, general, esfuerzo intenso" },


    //MISCELANEAS
{ cod: "09000", met: 1.5, cat: "Misceláneas", act: "Juegos de mesa, sentado" },
    { cod: "09005", met: 2.5, cat: "Misceláneas", act: "Juegos en casino, de pie" },
    { cod: "09010", met: 1.5, cat: "Misceláneas", act: "Juego de cartas, sentado" },
    { cod: "09013", met: 1.5, cat: "Misceláneas", act: "Juego de ajedréz, sentado" },
    { cod: "09015", met: 1.5, cat: "Misceláneas", act: "Fotocopiado de documentos, de pie" },
    { cod: "09020", met: 1.8, cat: "Misceláneas", act: "Dibujo, escritura, pintura, de pie" },
    { cod: "09025", met: 1.0, cat: "Misceláneas", act: "Reirse, sentado" },
    { cod: "09030", met: 1.3, cat: "Misceláneas", act: "Sentado, lectura de libro, periódico, etc" },
    { cod: "09040", met: 1.3, cat: "Misceláneas", act: "Sentado, escritura, trabajo de escritorio, tipeo" },
    { cod: "09045", met: 1.0, cat: "Misceláneas", act: "Sentado, uso de video juegos tradicionales, juegos en computadora" },
    { cod: "09050", met: 1.8, cat: "Misceláneas", act: "De pie, conversación (teléfono, texto, persona), ligero" },
    { cod: "09055", met: 1.5, cat: "Misceláneas", act: "De pie, conversación (teléfono, texto, persona), ligero" },
    { cod: "09060", met: 1.3, cat: "Misceláneas", act: "Sentado, estudiando, general, leyendo y/o escribiendo, ligero" },
    { cod: "09065", met: 1.8, cat: "Misceláneas", act: "Sentado, en clases, tomando nota o en discusión" },
    { cod: "09070", met: 1.8, cat: "Misceláneas", act: "De pie, lectura" },
    { cod: "09071", met: 2.5, cat: "Misceláneas", act: "De pie, misceláneas" },
    { cod: "09075", met: 1.8, cat: "Misceláneas", act: "Sentado, arte y artesanías, tallado, tejido, ligero" },
    { cod: "09080", met: 3.0, cat: "Misceláneas", act: "Sentado, arte y artesanías, tallado, tejido, moderado" },
    { cod: "09085", met: 2.5, cat: "Misceláneas", act: "De pie, arte y artesanías, pintura sobre arena, tallado, ligero" },
    { cod: "09090", met: 3.3, cat: "Misceláneas", act: "De pie, arte y artesanías, pintura sobre arena, tallado, moderado" },
    { cod: "09095", met: 3.5, cat: "Misceláneas", act: "De pie, arte y artesanías, pintura sobre arena, tallado, intenso" },
    { cod: "09100", met: 1.8, cat: "Misceláneas", act: "Reuniones familiares, sentado, relajado, conversando, comiendo" },
    { cod: "09101", met: 3.0, cat: "Misceláneas", act: "Reuniones familiares, juego con niños" },
    { cod: "09105", met: 2.0, cat: "Misceláneas", act: "Turismo/viaje/vacaciones conduciendo un vehículo" },
    { cod: "09106", met: 3.5, cat: "Misceláneas", act: "Turismo/viaje/vacaciones caminando" },
    { cod: "09110", met: 2.5, cat: "Misceláneas", act: "Camping, de pie, caminando, sentado, ligero a moderado" },
    { cod: "09115", met: 1.5, cat: "Misceláneas", act: "Sentado en evento deportivo, espectador" },

//INTRUMENTOS
{ cod: "10010", met: 1.8, cat: "Instrumentos Musicales", act: "Acordión, sentado" },
    { cod: "10020", met: 2.3, cat: "Instrumentos Musicales", act: "Violonchelo, sentado" },
    { cod: "10030", met: 2.3, cat: "Instrumentos Musicales", act: "Dirección de orquesta, de pie" },
    { cod: "10035", met: 2.5, cat: "Instrumentos Musicales", act: "Contrabajo, de pie" },
    { cod: "10040", met: 3.8, cat: "Instrumentos Musicales", act: "Batería, sentado" },
    { cod: "10045", met: 3.0, cat: "Instrumentos Musicales", act: "Percusión (bongo, conga, benbe), sentado, moderado" },
    { cod: "10050", met: 2.0, cat: "Instrumentos Musicales", act: "Flauta, sentado" },
    { cod: "10060", met: 1.8, cat: "Instrumentos Musicales", act: "Cuerno, de pie" },
    { cod: "10070", met: 2.3, cat: "Instrumentos Musicales", act: "Piano, sentado" },
    { cod: "10074", met: 2.0, cat: "Instrumentos Musicales", act: "Uso de instrumentos musicales, general" },
    { cod: "10077", met: 2.0, cat: "Instrumentos Musicales", act: "Órgano, sentado" },
    { cod: "10080", met: 3.5, cat: "Instrumentos Musicales", act: "Trombón, de pie" },
    { cod: "10090", met: 1.8, cat: "Instrumentos Musicales", act: "Trompeta, de pie" },
    { cod: "10100", met: 2.5, cat: "Instrumentos Musicales", act: "Violín, sentado" },
    { cod: "10110", met: 1.8, cat: "Instrumentos Musicales", act: "Instrumentos de viento, sentado" },
    { cod: "10120", met: 2.0, cat: "Instrumentos Musicales", act: "Guitarra, clásica o folklore, sentado" },
    { cod: "10125", met: 3.0, cat: "Instrumentos Musicales", act: "Guitarra, banda de rock and roll, de pie" },
    { cod: "10130", met: 4.0, cat: "Instrumentos Musicales", act: "Banda de desfile, giro de bastón, caminando" },
    { cod: "10131", met: 5.5, cat: "Instrumentos Musicales", act: "Banda de desfile, tocando instrumento, caminando rápido" },
    { cod: "10135", met: 3.5, cat: "Instrumentos Musicales", act: "Banda de desfile, tambor principal, caminando" },
//OCUPACION U OFICIOS

    { cod: "11003", met: 2.3, cat: "Ocupación u Oficios", act: "Trabajo activo con micro ordenador, escritorio con tapiz rodante, caminando" },
    { cod: "11006", met: 3.0, cat: "Ocupación u Oficios", act: "Azafata" },
    { cod: "11010", met: 4.0, cat: "Ocupación u Oficios", act: "Panadería, general, esfuerzo moderado" },
    { cod: "11015", met: 2.0, cat: "Ocupación u Oficios", act: "Panadería, esfuerzo ligero" },
    { cod: "11020", met: 2.3, cat: "Ocupación u Oficios", act: "Encuadernación" },
    { cod: "11030", met: 6.0, cat: "Ocupación u Oficios", act: "Construcción de carreteras, manejo de maquinaria pesada" },
    { cod: "11035", met: 2.0, cat: "Ocupación u Oficios", act: "Construcción de carreteras, dirección de tráfico, de pie" },
    { cod: "11038", met: 2.5, cat: "Ocupación u Oficios", act: "Carpintería, general, esfuerzo ligero" },
    { cod: "11040", met: 4.3, cat: "Ocupación u Oficios", act: "Carpintería, general, esfuerzo moderado" },
    { cod: "11042", met: 7.0, cat: "Ocupación u Oficios", act: "Carpintería, general, esfuerzo intenso" },
    { cod: "11050", met: 8.0, cat: "Ocupación u Oficios", act: "Transporte de cargas pesadas (ladrillos, herramientas)" },
    { cod: "11060", met: 8.0, cat: "Ocupación u Oficios", act: "Transporte de cargas moderadas subiendo escaleras (11-22 kg)" },
    { cod: "11070", met: 4.0, cat: "Ocupación u Oficios", act: "Camarero, empleado de hotel, armado de camas, limpieza, empuje de carro" },
    { cod: "11080", met: 5.3, cat: "Ocupación u Oficios", act: "Extracción de carbón, perforación y obtención de rocas" },
    { cod: "11090", met: 5.0, cat: "Ocupación u Oficios", act: "Extracción de carbón, uso de soporte" },
    { cod: "11100", met: 5.5, cat: "Ocupación u Oficios", act: "Extracción de carbón, general" },
    { cod: "11110", met: 6.3, cat: "Ocupación u Oficios", act: "Extracción de carbón, con pala" },
    { cod: "11115", met: 2.5, cat: "Ocupación u Oficios", act: "Cocina, chef" },
    { cod: "11120", met: 4.0, cat: "Ocupación u Oficios", act: "Construcción, exteriores del hogar, remodelado, nuevas estructuras" },
    { cod: "11125", met: 2.3, cat: "Ocupación u Oficios", act: "Servicio de portería, esfuerzo ligero (limpieza, aspiradora, plumero)" },
    { cod: "11126", met: 3.8, cat: "Ocupación u Oficios", act: "Servicio de portería, esfuerzo moderado (lustrar, barrer, trapear, basura)" },
    { cod: "11128", met: 2.0, cat: "Ocupación u Oficios", act: "Manejo de camión de reparto, taxi, ómnibus" },
    { cod: "11130", met: 3.3, cat: "Ocupación u Oficios", act: "Trabajo eléctrico (conexión de cables, redes eléctricas)" },
    { cod: "11135", met: 1.8, cat: "Ocupación u Oficios", act: "Ingeniería (mecánica o eléctrica)" },
    { cod: "11145", met: 7.8, cat: "Ocupación u Oficios", act: "Agricultura, esfuerzo intenso (empacado de heno, limpieza de establo)" },
    { cod: "11146", met: 4.8, cat: "Ocupación u Oficios", act: "Agricultura, esfuerzo moderado (alimentar animales, cosecha, abono)" },
    { cod: "11147", met: 2.0, cat: "Ocupación u Oficios", act: "Agricultura, esfuerzo ligero (limpieza de corrales, preparación alimento)" },
    { cod: "11170", met: 2.8, cat: "Ocupación u Oficios", act: "Agricultura, tareas de manejo (tractor o cosechadora)" },
    { cod: "11180", met: 3.5, cat: "Ocupación u Oficios", act: "Agricultura, alimentación de pequeños animales" },
    { cod: "11190", met: 4.3, cat: "Ocupación u Oficios", act: "Agricultura, alimentación de ganado, caballos" },
    { cod: "11191", met: 4.3, cat: "Ocupación u Oficios", act: "Agricultura, transporte de agua para animales y general" },
    { cod: "11192", met: 4.5, cat: "Ocupación u Oficios", act: "Agricultura, cuidado de animales (acicalado, esquilado, asistencia)" },
    { cod: "11195", met: 3.8, cat: "Ocupación u Oficios", act: "Agricultura, plantación de arróz, molienda de granos" },
    { cod: "11210", met: 3.5, cat: "Ocupación u Oficios", act: "Agricultura, ordeñado a mano, limpieza cubetas, esfuerzo moderado" },
    { cod: "11220", met: 1.3, cat: "Ocupación u Oficios", act: "Agricultura, ordeñado con ordeñadora, esfuerzo ligero" },
    { cod: "11240", met: 8.0, cat: "Ocupación u Oficios", act: "Bombero, general" },
    { cod: "11244", met: 6.8, cat: "Ocupación u Oficios", act: "Bombero, rescate víctimas, accidente vial, uso de herramientas" },
    { cod: "11245", met: 8.0, cat: "Ocupación u Oficios", act: "Bombero, ascenso con uniforme completo, entrenamiento simulación" },
    { cod: "11246", met: 9.0, cat: "Ocupación u Oficios", act: "Bombero, carga equipamiento, rotura muros, uso equipo completo" },
    { cod: "11247", met: 3.5, cat: "Ocupación u Oficios", act: "Pesca comercial, esfuerzo ligero" },
    { cod: "11248", met: 5.0, cat: "Ocupación u Oficios", act: "Pesca comercial, esfuerzo moderado" },
    { cod: "11249", met: 7.0, cat: "Ocupación u Oficios", act: "Pesca comercial, esfuerzo intenso" },
    { cod: "11250", met: 17.5, cat: "Ocupación u Oficios", act: "Forestación, corte con hacha muy rápido (51 golpes/min), extremadamente intenso" },
    { cod: "11260", met: 5.0, cat: "Ocupación u Oficios", act: "Forestación, corte con hacha lento (19 golpes/min), esfuerzo moderado" },
    { cod: "11262", met: 8.0, cat: "Ocupación u Oficios", act: "Forestación, corte con hacha rápido (35 golpes/min), esfuerzo intenso" },
    { cod: "11264", met: 4.5, cat: "Ocupación u Oficios", act: "Forestación, esfuerzo moderado (sierra eléctrica, desmalezado)" },
    { cod: "11266", met: 8.0, cat: "Ocupación u Oficios", act: "Forestación, esfuerzo intenso (talado, transporte de troncos, sierra manual)" },
    { cod: "11370", met: 4.5, cat: "Ocupación u Oficios", act: "Peletería" },
    { cod: "11375", met: 4.0, cat: "Ocupación u Oficios", act: "Recolección de basura, caminando, arrojando basura al camión" },
    { cod: "11378", met: 1.8, cat: "Ocupación u Oficios", act: "Estilista de cabello (trenzado, manicuría, cosmetología)" },
    { cod: "11380", met: 7.3, cat: "Ocupación u Oficios", act: "Acicalado, alimentación, limpieza y entrenamiento de caballos" },
    { cod: "11381", met: 4.3, cat: "Ocupación u Oficios", act: "Alimentación de caballos, limpieza de casilla, transportando cargas" },
    { cod: "11390", met: 7.3, cat: "Ocupación u Oficios", act: "Carrera de caballos, galope" },
    { cod: "11400", met: 5.8, cat: "Ocupación u Oficios", act: "Carrera de caballos, trote" },
    { cod: "11410", met: 3.8, cat: "Ocupación u Oficios", act: "Carrera de caballos, caminata" },
    { cod: "11413", met: 3.0, cat: "Ocupación u Oficios", act: "Servicio de cocina" },
    { cod: "11415", met: 4.0, cat: "Ocupación u Oficios", act: "Jardinería, trabajo de jardín, general" },
    { cod: "11418", met: 3.3, cat: "Ocupación u Oficios", act: "Empleado de lavandería" },
    { cod: "11420", met: 3.0, cat: "Ocupación u Oficios", act: "Cerrajero" },
    { cod: "11430", met: 3.0, cat: "Ocupación u Oficios", act: "Operador de máquinas (metal, tornería, soldado), ligero a moderado" },
    { cod: "11450", met: 5.0, cat: "Ocupación u Oficios", act: "Operario de máquinas, prensado, esfuerzo moderado" },
    { cod: "11472", met: 1.8, cat: "Ocupación u Oficios", act: "Administrador de propiedades" },
    { cod: "11475", met: 2.8, cat: "Ocupación u Oficios", act: "Trabajo manual o no cualificado, general, esfuerzo ligero" },
    { cod: "11476", met: 4.5, cat: "Ocupación u Oficios", act: "Trabajo manual o no cualificado, general, esfuerzo moderado" },
    { cod: "11477", met: 6.5, cat: "Ocupación u Oficios", act: "Trabajo manual o no cualificado, general, esfuerzo intenso" },
    { cod: "11480", met: 4.3, cat: "Ocupación u Oficios", act: "Albañilería, hormigón, esfuerzo moderado" },
    { cod: "11482", met: 2.5, cat: "Ocupación u Oficios", act: "Albañilería, hormigón, esfuerzo ligero" },
    { cod: "11485", met: 4.0, cat: "Ocupación u Oficios", act: "Masajista terapéutico, de pie" },
    { cod: "11490", met: 7.5, cat: "Ocupación u Oficios", act: "Mudanza, transporte o empuje de objetos pesados (34 kg o más)" },
    { cod: "11495", met: 12.0, cat: "Ocupación u Oficios", act: "Buceo o submarinismo, agentes de marina" },
    { cod: "11500", met: 2.5, cat: "Ocupación u Oficios", act: "Operario de equipamiento pesado, automatizado, sin manejo" },
    { cod: "11510", met: 4.5, cat: "Ocupación u Oficios", act: "Trabajo en plantación de naranjos, recolección de frutas" },
    { cod: "11514", met: 3.3, cat: "Ocupación u Oficios", act: "Pintura de casa o muebles, esfuerzo moderado" },
    { cod: "11516", met: 3.0, cat: "Ocupación u Oficios", act: "Plomería" },
    { cod: "11520", met: 2.0, cat: "Ocupación u Oficios", act: "Impresiones, trabajador de la industria del papel, de pie" },
    { cod: "11525", met: 2.5, cat: "Ocupación u Oficios", act: "Policía, dirección de tráfico, de pie" },
    { cod: "11526", met: 2.5, cat: "Ocupación u Oficios", act: "Policía, manejo de patrulla, sentado" },
    { cod: "11527", met: 1.3, cat: "Ocupación u Oficios", act: "Policía, acompañante de patrulla, sentado" },
    { cod: "11528", met: 4.0, cat: "Ocupación u Oficios", act: "Policía, en actividad de arresto, de pie" },
    { cod: "11529", met: 2.3, cat: "Ocupación u Oficios", act: "Cartero, entrega de cartas caminando" },
    { cod: "11530", met: 2.0, cat: "Ocupación u Oficios", act: "Zapatero, general" },
    { cod: "11540", met: 7.8, cat: "Ocupación u Oficios", act: "Uso de la pala, cavar un hoyo" },
    { cod: "11550", met: 8.8, cat: "Ocupación u Oficios", act: "Uso de la pala, más de 7 kg/min, cavado profundo, intenso" },
    { cod: "11560", met: 5.0, cat: "Ocupación u Oficios", act: "Uso de la pala, menos de 4,5 kg/min, esfuerzo moderado" },
    { cod: "11570", met: 6.5, cat: "Ocupación u Oficios", act: "Uso de la pala, 4,5 a 7 kg/min, esfuerzo intenso" },
    { cod: "11580", met: 1.5, cat: "Ocupación u Oficios", act: "Tareas sentado, ligero (oficina, laboratorio, reparación relojes)" },
    { cod: "11585", met: 1.5, cat: "Ocupación u Oficios", act: "Reuniones, sentado, ligero, general, conversando" },
    { cod: "11590", met: 2.5, cat: "Ocupación u Oficios", act: "Tareas sentado, moderado (palancas pesadas, montacargas, grúas)" },
    { cod: "11593", met: 2.8, cat: "Ocupación u Oficios", act: "Sentado, enseñanza de stretching, yoga o ejercicios ligeros" },
    { cod: "11600", met: 3.0, cat: "Ocupación u Oficios", act: "Tareas de pie, ligero (barra bar, archivo, biblioteca, copiado)" },
    { cod: "11610", met: 3.0, cat: "Ocupación u Oficios", act: "De pie, ligero/moderado (reparación partes pesadas, soldadura, empaque)" },
    { cod: "11615", met: 4.5, cat: "Ocupación u Oficios", act: "De pie, movilización de objetos contínuamente (4,5-9 Kg)" },
    { cod: "11620", met: 3.5, cat: "Ocupación u Oficios", act: "De pie, movilización intermitente de objetos de 23 Kg" },
    { cod: "11630", met: 4.5, cat: "Ocupación u Oficios", act: "De pie, tareas moderadas/intensas (más de 23 Kg, albañilería)" },
    { cod: "11708", met: 5.3, cat: "Ocupación u Oficios", act: "Trabajo del acero, esfuerzo moderado (moldeado, forjado)" },
    { cod: "11710", met: 8.3, cat: "Ocupación u Oficios", act: "Trabajo del acero, intenso (laminado mano, remoción escombros)" },
    { cod: "11720", met: 2.3, cat: "Ocupación u Oficios", act: "Sastrería, corte de tela" },
    { cod: "11730", met: 2.5, cat: "Ocupación u Oficios", act: "Sastrería, general" },
    { cod: "11740", met: 1.8, cat: "Ocupación u Oficios", act: "Sastrería, costura manual" },
    { cod: "11750", met: 2.5, cat: "Ocupación u Oficios", act: "Sastrería, con máquina de coser" },
    { cod: "11760", met: 3.5, cat: "Ocupación u Oficios", act: "Sastrería, planchado" },
    { cod: "11763", met: 2.0, cat: "Ocupación u Oficios", act: "Sastrería, tejido ligero (lavado, teñido, inspección ropa)" },
    { cod: "11765", met: 4.0, cat: "Ocupación u Oficios", act: "Sastrería, tejido moderado (hilado, transporte cajas hilo)" },
    { cod: "11766", met: 6.5, cat: "Ocupación u Oficios", act: "Carga y descarga de camiones, soportar y transportar cargas pesadas" },
    { cod: "11767", met: 2.0, cat: "Ocupación u Oficios", act: "Manejo de camiones repartidores, taxi, colectivos, escolares" },
    { cod: "11770", met: 1.3, cat: "Ocupación u Oficios", act: "Tipeo, eléctrico, manual o en computadora" },
    { cod: "11780", met: 6.3, cat: "Ocupación u Oficios", act: "Uso de herramientas neumáticas pesadas (martillos, taladros)" },
    { cod: "11790", met: 8.0, cat: "Ocupación u Oficios", act: "Uso de herramientas pesadas no eléctricas (pala, pico, palancas)" },
    { cod: "11791", met: 2.0, cat: "Ocupación u Oficios", act: "Caminata en el trabajo (menor a 3 km/h), oficina o laboratorio" },
    { cod: "11792", met: 3.5, cat: "Ocupación u Oficios", act: "Caminata en el trabajo (5 km/h), oficina, sin transporte de objetos" },
    { cod: "11793", met: 4.3, cat: "Ocupación u Oficios", act: "Caminata en el trabajo (5,6 km/h), oficina, rápida, sin objetos" },
    { cod: "11795", met: 3.5, cat: "Ocupación u Oficios", act: "Caminata en el trabajo (4 km/h), transportando objetos < 11 Kg" },
    { cod: "11796", met: 3.0, cat: "Ocupación u Oficios", act: "Caminata, recogiendo objetos para el trabajo" },
    { cod: "11797", met: 3.8, cat: "Ocupación u Oficios", act: "Caminata (4 km/h), transportando objetos pesados > 11 Kg" },
    { cod: "11800", met: 4.5, cat: "Ocupación u Oficios", act: "Caminata (5 km/h), transportando objetos livianos < 11 Kg" },
    { cod: "11805", met: 3.5, cat: "Ocupación u Oficios", act: "Caminata, empujando una silla de ruedas" },
    { cod: "11810", met: 4.8, cat: "Ocupación u Oficios", act: "Caminata (5,6 km/h), rápida, transportando objetos < 11 Kg" },
    { cod: "11820", met: 5.0, cat: "Ocupación u Oficios", act: "Caminata o escaleras, transportando objetos entre 11 y 22 Kg" },
    { cod: "11830", met: 6.5, cat: "Ocupación u Oficios", act: "Caminata o escaleras, transportando objetos entre 22,6 y 33,5 kg" },
    { cod: "11840", met: 7.5, cat: "Ocupación u Oficios", act: "Caminata o escaleras, transportando objetos entre 34 y 45 Kg" },
    { cod: "11850", met: 8.5, cat: "Ocupación u Oficios", act: "Caminata o escaleras, transportando objetos de 45 kg o mayores" },
    { cod: "11870", met: 3.0, cat: "Ocupación u Oficios", act: "Preparación de escena, actor de teatro, empleado detrás de cámaras" },


    //CARRERA
{ cod: "12010", met: 6.0, cat: "Carrera", act: "Combinación de trote/caminata (trote menor a 10 min)" },
    { cod: "12020", met: 7.0, cat: "Carrera", act: "Trote, general" },
    { cod: "12025", met: 8.0, cat: "Carrera", act: "Trote, sin desplazamiento" },
    { cod: "12027", met: 4.5, cat: "Carrera", act: "Trote, sobre un mini-tramp" },
    { cod: "12029", met: 6.0, cat: "Carrera", act: "Correr, 6,5 km/h (9 min/km)" },
    { cod: "12030", met: 8.3, cat: "Carrera", act: "Correr, 8 km/h (7,5 min/km)" },
    { cod: "12040", met: 9.0, cat: "Carrera", act: "Correr, 8,4 km/h (7,3 min/km)" },
    { cod: "12050", met: 9.8, cat: "Carrera", act: "Correr, 9,6 km/h (6,3 min/km)" },
    { cod: "12060", met: 10.5, cat: "Carrera", act: "Correr, 10,8 km/h (5,5 min/km)" },
    { cod: "12070", met: 11.0, cat: "Carrera", act: "Correr, 11,3 km/h (5,3 min/km)" },
    { cod: "12080", met: 11.5, cat: "Carrera", act: "Correr, 12 km/h (5 min/km)" },
    { cod: "12090", met: 11.8, cat: "Carrera", act: "Correr, 12,9 km/h (4,7 min/km)" },
    { cod: "12100", met: 12.3, cat: "Carrera", act: "Correr, 13,8 km/h (4,3 min/km)" },
    { cod: "12110", met: 12.8, cat: "Carrera", act: "Correr, 14,5 km/h (4,1 min/km)" },
    { cod: "12120", met: 14.5, cat: "Carrera", act: "Correr, 16 km/h (3,8 min/km)" },
    { cod: "12130", met: 16.0, cat: "Carrera", act: "Correr, 17,7 km/h (3,4 min/km)" },
    { cod: "12132", met: 19.0, cat: "Carrera", act: "Correr, 19,3 km/h (3,1 min/km)" },
    { cod: "12134", met: 19.8, cat: "Carrera", act: "Correr, 20,9 km/h (2,9 min/km)" },
    { cod: "12135", met: 23.0, cat: "Carrera", act: "Correr, 22,5 km/h (2,6 min/km)" },
    { cod: "12140", met: 9.0, cat: "Carrera", act: "Correr, cross country" },
    { cod: "12150", met: 8.0, cat: "Carrera", act: "Correr (Código Taylor 200)" },
    { cod: "12170", met: 15.0, cat: "Carrera", act: "Correr, subiendo escaleras" },
    { cod: "12180", met: 10.0, cat: "Carrera", act: "Correr, sobre una cinta, entrenamiento en grupo" },
    { cod: "12190", met: 8.0, cat: "Carrera", act: "Correr, entrenamiento, empujando silla o carro" },
    { cod: "12200", met: 13.3, cat: "Carrera", act: "Correr, maratón" },

//CUIDADO PERSONAL

    { cod: "13000", met: 2.3, cat: "Cuidado Personal", act: "Preparación para irse a la cama, general, de pie" },
    { cod: "13009", met: 1.8, cat: "Cuidado Personal", act: "En el toilet, evacuando de pié o en semi flexión" },
    { cod: "13010", met: 1.5, cat: "Cuidado Personal", act: "Bañarse, sentado" },
    { cod: "13020", met: 2.5, cat: "Cuidado Personal", act: "Vestirse, desvestirse, de pie o sentado" },
    { cod: "13030", met: 1.5, cat: "Cuidado Personal", act: "Comer, sentado" },
    { cod: "13035", met: 2.0, cat: "Cuidado Personal", act: "Conversar y comer o comer solamente, de pie" },
    { cod: "13036", met: 1.5, cat: "Cuidado Personal", act: "Ingesta de medicamentos, sentado o de pie" },
    { cod: "13040", met: 2.0, cat: "Cuidado Personal", act: "Acicalarse, lavar manos, afeitarse, dientes, maquillaje" },
    { cod: "13045", met: 2.5, cat: "Cuidado Personal", act: "Peinarse, de pie" },
    { cod: "13046", met: 1.3, cat: "Cuidado Personal", act: "Peinado y manicuría realizados por otra persona, sentado" },
    { cod: "13050", met: 2.0, cat: "Cuidado Personal", act: "Ducharse, secarse, de pie" },


//ACTIVIDAD SEXUAL

    {cod: "14010", met: 2.8, cat: "Actividad Sexual", act: "Sujeto activo, esfuerzo intenso"},
    {cod: "14020", met: 1.8, cat:"Actividad Sexual" , act: "General, esfuerzo moderado"},
    {cod: "14030", met: 1.3, cat: "Actividad Sexual", act: "Sujeto pasivo, esfuerzo ligero, besarse, abrazarse"},
   
    
//DEPORTES

    {cod: "15000", met: 5.5, cat: "Deportes", act: "Juegos originarios de Alaska, Juegos olímpicos esquimales, general"},
    {cod: "15010", met: 4.3, cat: "Deportes", act: "Arquería, no de caza"},
    {cod: "15020", met: 7.0, cat: "Deportes", act: "Bádminton, competitivo (Código Taylor 450)"},
    {cod: "15030", met: 5.5, cat: "Deportes", act: "Bádminton, dobles y singles, general"},
    {cod: "15040", met: 8.0, cat: "Deportes", act: "Baloncesto, partido (Código Taylor 490)" },
    {cod: "15050", met: 6.0, cat: "Deportes", act: "Baloncesto, no en partido, general (Código Taylor 480)"},
    {cod: "15055", met: 6.5, cat: "Deportes", act: "Baloncesto, general"},
    {cod: "15060", met: 7.0, cat: "Deportes", act: "Baloncesto, arbitraje (Código Taylor 500)"},
    {cod: "15070", met: 4.5, cat: "Deportes", act: "Baloncesto, tiros al cesto"},
    {cod: "15072", met: 9.3, cat: "Deportes", act: "Baloncesto, drills de práctica"},
    {cod: "15075", met: 7.8, cat: "Deportes", act: "Baloncesto, en silla de ruedas"},
    {cod: "15080", met: 2.5, cat: "Deportes", act: "Billar"},
    {cod: "15090", met: 3.0, cat: "Deportes", act: "Bowling (Código Taylor 390)"},
    {cod: "15092", met: 3.8, cat: "Deportes", act: "Bowling, indoor, en pista"},
    {cod: "15100", met: 12.8, cat:"Deportes", act: "Boxeo, en cuadrilátero, general"},
    {cod: "15110", met: 5.5, cat: "Deportes", act: "Boxeo, entrenamiento con bolsa"},
    {cod: "15120", met: 7.8, cat: "Deportes", act: "Boxeo, sparring"},
    {cod: "15130", met: 7.0, cat: "Deportes", act: "Broomball"},
    {cod: "15135", met: 5.8, cat: "Deportes", act: "Juegos de niños, juegos de adultos (ej: Rayuela, 4 cuadrados, Mancha con pelota, juegos en patio de recreos,T-ball ,tetherball, canicas, maquinitas), esfuerzo moderado" },
    {cod: "15138", met: 6.0, cat: "Deportes", act: "Exhibiciones gimnásticas de animación, ejercicios de gimnasia, competición"},
    {cod: "15140", met: 4.0, cat: "Deportes", act: "Entrenador, fútbol Americano, fútbol, baloncesto, natación, etc"},
    {cod: "15142", met: 8.0, cat: "Deportes", act: "Entrenador, en actividad con los jugadores"},
    {cod: "15150", met: 4.8, cat: "Deportes", act: "Críquet, batear, lanzar, interceptar y devolver"},
    {cod: "15160", met: 3.3, cat: "Deportes", act: "Croquet"},
    {cod: "15170", met: 4.0, cat: "Deportes", act: "Curling"},
    {cod: "15180", met: 2.5, cat: "Deportes", act: "Dardos, sobre pared o césped"},
    {cod: "15190", met: 6.0, cat: "Deportes", act: "Picadas automovilísticas, empujando o conduciendo el auto"},
    {cod: "15192", met: 8.5, cat: "Deportes", act: "Automovilismo, del tipo fórmula uno"},
    {cod: "15200", met: 6.0, cat: "Deportes", act: "Esgrima"},
    {cod: "15210", met: 8.0, cat: "Deportes", act: "Fútbol Americano, competitivo"},
    {cod: "15230", met: 8.0, cat: "Deportes", act: "Fútbol Americano, tocata, flag, general (Código Taylor 510)"},
    {cod: "15232", met: 4.0, cat: "Deportes", act: "Fútbol Americano, tocata, flag, esfuerzo ligero"},
    {cod: "15235", met: 2.5, cat: "Deportes", act: "Fútbol Americano o Baseball, atrapar la peolota con el guante"},
    {cod: "15240", met: 3.0, cat: "Deportes", act: "Frisbee, general"},
    {cod: "15250", met: 8.0, cat: "Deportes", act: "Frisbee, ultimate"},
    {cod: "15255", met: 4.8, cat: "Deportes", act: "Golf, general"},
    {cod: "15265", met: 4.3, cat: "Deportes", act: "Golf, caminar, transportar palos de golf"},
    {cod: "15270", met: 3.0, cat: "Deportes", act: "Golf, minigolf, driving range"},
    {cod: "15285", met: 5.3, cat: "Deportes", act: "Golf, caminar, transporte de palos de golf"},
    {cod: "15290", met: 3.5, cat: "Deportes", act: "Golf, uso de vehículo motorizado (Código Taylor 070)"},
    {cod: "15300", met: 3.8, cat: "Deportes", act: "Gimnasia, general"},
    {cod: "15310", met: 4.0, cat: "Deportes", act: "Footbag"},
    {cod: "15320", met: 12.0, cat: "Deportes",act: "Handball, general (Código Taylor 520)"},
    {cod: "15330", met: 8.0, cat: "Deportes", act: "Handball, en equipo"},
    {cod: "15335", met: 4.0, cat: "Deportes", act: "Circuito High Ropes, múltiples elementos"},
    {cod: "15350", met: 7.8, cat: "Deportes", act: "Hockey, sobre césped"},
    {cod: "15360", met: 8.0, cat: "Deportes", act: "Hockey, sobre hielo, general"},
    {cod: "15362", met: 10.0, cat: "Deportes", act: "Hockey, sobre hielo, competitivo"},
    {cod: "15370", met: 5.5, cat: "Deportes", act: "Equitación, general"},
    {cod: "15375", met: 4.3, cat: "Deportes", act: "Mantenimiento de caballos, comida, bebida, limpieza de corral, caminando y movilizando cargas"},
    {cod: "15380", met: 4.5, cat: "Deportes", act: "Ensillar, acicalar, colocar y sacar el arnés al caballo"},
    {cod: "15390", met: 5.8, cat: "Deportes", act: "Equitación, trote"},
    {cod: "15395", met: 7.3, cat: "Deportes", act: "Equitación,medio galope o galope"},
    {cod: "15400", met: 3.8, cat: "Deportes", act: "Equitación, caminata"},
    {cod: "15402", met: 9.0, cat: "Deportes", act: "Equitación, saltos"},
    {cod: "15408", met: 1.8, cat: "Deportes", act: "Carro de caballos, manejo, sentado o de pie"},
    {cod: "15410", met: 3.0, cat: "Deportes", act: "Lanzamiento de herradura, de anillos"},
    {cod: "15420", met: 12.0, cat: "Deportes", act: "Pelota Vasca"},
    {cod: "15425", met: 5.3, cat: "Deportes", act: "Artes marciales, diferentes tipos, ritmo lento, principiantes, práctica"},
    {cod: "15430", met: 10.3, cat: "Deportes", act: "Artes marciales, diferentes tipos, ritmo moderado (ej: judo, jujitsu, karate, kick boxing, tae kwan do, tai-bo, Muay Thai boxing)"},
    {cod: "15440", met: 4.0, cat: "Deportes", act: "Malabarismo"},
    {cod: "15450", met: 7.0, cat: "Deportes", act: "Kickball"},
    {cod: "15460", met: 8.0, cat: "Deportes", act: "Lacrosse"},
    {cod: "15465", met: 3.3, cat: "Deportes", act: "Bowls, bocce, al aire libre"},
    {cod: "15470", met: 4.0, cat: "Deportes", act: "Moto-cross, deportes motorizados fuera de carretera, vehículos todo terreno, general"},
    {cod: "15480", met: 9.0, cat: "Deportes", act: "Orienteering"},
    {cod: "15490", met: 10.0, cat: "Deportes", act: "Paddle, competitivo"},
    {cod: "15500", met: 6.0, cat: "Deportes", act: "Paddle, casual, general (Código Taylor 460)"},
    {cod: "15510", met: 8.0, cat: "Deportes", act: "Polo, a caballo"},
    {cod: "15520", met: 10.0, cat: "Deportes", act: "Racquetball, competitivo"},
    {cod: "15530", met: 7.0, cat: "Deportes", act: "Racquetball, general (Código Taylor 470)"},
    {cod: "15533", met: 8.0, cat: "Deportes", act: "Escalada, sobre roca o montaña (Código Taylor 470) (Ex-Código: 17120)"},
    {cod: "15535", met: 7.5, cat: "Deportes", act: "Escalada, ascenso sobre roca, elevada dificultad"},
    {cod: "15537", met: 5.8, cat: "Deportes", act: "Escalada, en ascenso o cruzando rocas, baja a moderada dificultad"},
    {cod: "15540", met: 5.0, cat: "Deportes", act: "Escalada, en descenso"},
    {cod: "15542", met: 4.0, cat: "Deportes", act: "Deportes de rodeo, general, esfuerzo ligero"},
    {cod: "15544", met: 5.5, cat: "Deportes", act: "Deportes de rodeo, general, esfuerzo moderado"},
    {cod: "15546", met: 7.0, cat: "Deportes", act: "Deportes de rodeo, general, esfuerzo intenso"},
    {cod: "15550", met: 12.3, cat: "Deportes", act: "Salto a la cuerda, ritmo rápido, 120-160 saltos/min"},
    {cod: "15551", met: 11.8, cat: "Deportes", act: "Salto a la cuerda, ritmo moderado, 100-120 saltos/min, general, salto a 2 pies, en superficie plana"},
    {cod: "15552", met: 8.8, cat: "Deportes", act: "Salto a la cuerda, ritmo lento, < 100 saltos/min, salto a 2 pies, rebote rítmico"},
    {cod: "15560", met: 8.3, cat: "Deportes", act: "Rugby, unión, en equipo, competitivo"},
    {cod: "15562", met: 6.3, act: "Deportes", act: "Rugby, tocata, no competitivo"},
    {cod: "15570", met: 3.0, cat: "Deportes", act: "Tejo"}, 
    {cod: "15580", met: 5.0, cat: "Deportes", act: "Patineta, general, esfuerzo moderado"},
    {cod: "15582", met: 6.0, cat: "Deportes", act:  "Patineta, competitivo, esfuerzo intenso"},
    {cod: "15590", met: 7.0, cat: "Deportes", act: "Patinaje, sobre ruedas (Código Taylor 360)"},
    {cod: "15591", met: 7.5, cat: "Deportes", act: "Patinaje, sobre ruedas, en línea, 14.4 km/h, ritmo ligero"},
    {cod: "15592", met: 9.8, cat: "Deportes", act: "Patinaje, sobre ruedas, en línea, 17.7 km/h, ritmo moderado, entrenamiento"},
    {cod: "15593", met: 12.3, cat: "Deportes", act: "Patinaje, sobre ruedas, en línea, 21.0 to 21.7 km/h, ritmo rápido, entrenamiento"},
    {cod: "15594", met: 14.0, cat: "Deportes", act: "Patinaje, sobre ruedas, en línea, 24.0 km/h, máximo esfuerzo"},
    {cod: "15600", met: 3.5, cat: "Deportes", act: "Paracaidismo, base jumping, bungee jumping"},
    {cod: "15605", met: 10.0,cat: "Deportes", act: "Fútbol, competitivo"},
    {cod: "15610", met: 7.0, cat: "Deportes", act: "Fútbol, casual, general (Codigo Taylor 540)"},
    {cod: "15620", met: 5.0, cat: "Deportes", act: "Softball o Baseball, lanzamiento rápido o lento, general (Código Taylor 440)"},
    {cod: "15625", met: 4.0, cat: "Deportes", act: "Softball, práctica"},
    {cod: "15630", met: 4.0, cat: "Deportes", act: "Softball, arbitraje"},
    {cod: "15640", met: 6.0, cat: "Deportes", act: "Softball, lanzamiento"},
    {cod: "15645", met: 3.3, cat: "Deportes", act: "Espectador deportivo, muy ansioso, emocionado, movedizo"},
    {cod: "15650", met: 12.0, cat: "Deportes",act: "Squash (Código Taylor 530)"},
    {cod: "15652", met: 7.3, cat: "Deportes", act: "Squash. General"},
    {cod: "15660", met: 4.0, cat: "Deportes", act: "Tenis de mesa, ping pong (Código Taylor 410)"},
    {cod: "15670", met: 3.0, cat: "Deportes", act: "Tai chi, qi gong, general"},
    {cod: "15672", met: 1.5, cat: "Deportes", act: "Tai chi, qi gong, sentado, esfuerzo ligero"},
    {cod: "15675", met: 7.3, cat: "Deportes", act: "Tennis, general"},
    {cod: "15680", met: 6.0, cat: "Deportes", act: "Tennis, dobles (Código Taylor 430)"},
    {cod: "15685", met: 4.5, cat: "Deportes", act: "Tennis, dobles"},
    {cod: "15690", met: 8.0, cat: "Deportes", act: "Tennis,singles (Código Taylor 420)"},
    {cod: "15695", met: 5.0, cat: "Deportes", act: "Tennis,pegarle a la pelota, no en juego, esfuerzo moderado"},
    {cod: "15700", met: 3.5, cat: "Deportes", act: "Trampolín, recreativo"},
    {cod: "15702", met: 4.5, cat: "Deportes", act: "Trampolín, competitivo"},
    {cod: "15710", met: 4.0, cat: "Deportes", act: "Volley (Código Taylor 400)"},
    {cod: "15711", met: 6.0, cat: "Deportes", act: "Volley, competitivo, en salón"},
    {cod: "15720", met: 3.0, cat: "Deportes", act: "Volley, no competitivo, equipo de 6-9 jugadores, general"},
    {cod: "15725", met: 8.0, cat: "Deportes", act: "Volley, en la playa, en arena"},
    {cod: "15730", met: 6.0, cat: "Deportes", act: "Lucha (un match: 5 minutos)"},
    {cod: "15731", met: 7.0, cat: "Deportes", act: "Voley-pared, general"},
    {cod: "15732", met: 4.0, cat: "Deportes", act: "Atletismo (ej: lanzamientos, disco, martillo)"},
    {cod: "15733", met: 6.0, cat: "Deportes", act: "Atletismo (ej: salto en alto, salto en largo, salto triple, javalina, salto con garrocha )"},
    {cod: "15734", met: 10.0, cat: "Deportes", act: "Atletismo (ej: carrera con obstáculos, vallas)"},

  //TRANSPORTE
    {cod: "16010", met: 2.5, cat: "Transporte", act: "Conducir un auto o camión liviano (no un remolque)"},
    {cod: "16015", met: 1.3, cat: "Transporte", act: "Viajar en auto o en camión"},
    {cod: "16016", met: 1.3, cat: "Transporte", act: "Viajar en ómnibus o tren"},
    {cod: "16020", met: 1.8, cat: "Transporte", act: "Volar en avión o helicóptero"},
    {cod: "16030", met: 3.5, cat: "Transporte", act: "Motocicleta"},
    {cod: "16035", met: 6.3, cat: "Transporte", act: "Tirar del carruaje"},
    {cod: "16040", met: 6.0, cat: "Transporte", act: "Empujar un aeroplano dentro o fuera del hangar"},
    {cod: "16050", met: 2.5, cat: "Transporte", act: "Conducir un camión, remolque, tractor, > 1 tonelada, u ómnibus"},
    {cod: "16060", met: 3.5, cat: "Transporte", act: "Caminar para transportarse, 4,5 a 5 km/h, ritmo moderado, superficie estable"},


  //CAMINATA
    {cod: "17010", met: 7.0, cat: "Caminata", act: "Caminata con mochila (Código Taylor 050)"},
    {cod: "17012", met: 7.8, cat: "Caminata", act: "Caminata con mochila, de excursión o caminata organizada con mochila pequeña"},
    {cod: "17020", met: 5.0, cat: "Caminata", act: "Transporte de cargas de 7 Kg (ej: maleta), en llano o bajando escaleras"},
    {cod: "17021", met: 2.3, cat: "Caminata", act: "Transporte de niños de 7 Kg, caminata lenta"},
    {cod: "17025", met: 8.3, cat: "Caminata", act: "Transporte de cargas subiendo escaleras, general"},
    {cod: "17026", met: 5.0, cat: "Caminata", act: "Transporte de cargas de 0,5-7 Kg, subiendo escaleras"},
    {cod: "17027", met: 6.0, cat: "Caminata", act: "Transporte de cargas de 7-11 Kg, subiendo escaleras"},
    {cod: "17028", met: 8.0, cat: "Caminata", act: "Transporte de cargas de 11-22 Kg, subiendo escaleras"},
    {cod: "17029", met: 10.0, cat: "Caminata", act: "Transporte de cargas de 22-33 Kg, subiendo escaleras"},
    {cod: "17030", met: 12.0, cat: "Caminata", act: "Transporte de cargas > 34 Kg,subiendo escaleras"},
    {cod: "17031", met: 3.5, cat: "Caminata", act: "Carga/descarga de un auto, con desplazamiento"},
    {cod: "17033", met: 6.3, cat: "Caminata", act: "Ascenso de colinas, sin carga"},
    {cod: "17035", met: 6.5, cat: "Caminata", act: "Ascenso en colina con cargas de 0-4,5 Kg"},
    {cod: "17040", met: 7.3, cat: "Caminata", act: "Ascenso en colina con cargas de 4,5-9 Kg"},
    {cod: "17050", met: 8.3, cat: "Caminata", act: "Ascenso en colina con cargas de 9,5-19 Kg"},
    {cod: "17060", met: 9.0, cat: "Caminata", act: "Ascenso en colina con cargas mayores de 19 Kg"},
    {cod: "17070", met: 3.5, cat: "Caminata", act: "Descenso de escaleras"},
    {cod: "17080", met: 6.0, cat: "Caminata", act: "Excursionismo, a campo traviesa (Código Taylor 040)"},
    {cod: "17082", met: 5.3, cat: "Caminata", act: "Excursionismo o caminata a paso normal en campo y colina"},
    {cod: "17085", met: 2.5, cat: "Caminata", act: "Observación de pájaros, paso lento"},
    {cod: "17088", met: 4.5, cat: "Caminata", act: "Marcha militar, velocidad moderada, sin carga"},
    {cod: "17090", met: 8.0, cat: "Caminata", act: "Marcha militar rápida, sin carga"},
    {cod: "17100", met: 4.0, cat: "Caminata", act: "Empujar o Jalar un carro con niño dentro o caminar con niños, 4 a 5 km/h"},
    {cod: "17105", met: 3.8, cat: "Caminata", act: "Empujar una silla de ruedas, no laboralmente"},
    {cod: "17110", met: 6.5, cat: "Caminata", act: "Marcha atlética"},
    {cod: "17130", met: 8.0, cat: "Caminata", act: "Ascenso de escaleras, usando una escalera de mano (Código Taylor 030)"},
    {cod: "17133", met: 4.0, cat: "Caminata", act: "Ascenso de escaleras, paso lento"},
    {cod: "17134", met: 8.8, cat: "Caminata", act: "Ascenso de escaleras, paso rápido"},
    {cod: "17140", met: 5.0, cat: "Caminata", act: "Uso de muletas"},
    {cod: "17150", met: 2.0, cat: "Caminata", act: "Caminata, retorno al hogar"},
    {cod: "17151", met: 2.0, cat: "Caminata", act: "Caminata, a menos de 3 km/h, en llano, paseo, muy lento"},
    {cod: "17152", met: 2.8, cat: "Caminata", act: "Caminata, a 3 km/h, en llano, paso lento, superficie firme"},
    {cod: "17160", met: 3.5, cat: "Caminata", act: "Caminata por placer (Código Taylor 010)"},
    {cod: "17161", met: 2.5, cat: "Caminata", act: "Caminata desde el hogar hacia el auto u ómnibus, desde auto u ómnibus a diferentes sitios, o hacia y desde el trabajo"},
    {cod: "17162", met: 2.5, cat: "Caminata", act: "Caminata hacia el hogar de un vecino por razones sociales"},
    {cod: "17165", met: 3.0, cat: "Caminata", act: "Caminata con el perro"},
    {cod: "17170", met: 3.0, cat: "Caminata", act: "Caminata, 4 km/h, en llano, superficie firme"},
    {cod: "17180", met: 3.3, cat: "Caminata", act: "Caminata, 4 Km/h, en descenso"},
    {cod: "17190", met: 3.5, cat: "Caminata", act: "Caminata, 4,5–5 km/h, en llano, paso moderado, superficie firme"},
    {cod: "17200", met: 4.3, cat: "Caminata", act: "Caminata, 5,5 km/h, en llano, paso rápido, superficie firme, caminata como ejercicio"},
    {cod: "17210", met: 5.3, cat: "Caminata", act: "Caminata, 4,5 a 5,5 km/h, en escenso, pendiente 1-5%"},
    {cod: "17211", met: 8.0, cat: "Caminata", act: "Caminata, 4,5 a 5,5 km/h, en escenso, pendiente 6-15%"},
    {cod: "17220", met: 5.0, cat: "Caminata", act: "Caminata, 6,5 km/h, en llano, superficie firme, paso muy rápido"},
    {cod: "17230", met: 7.0, cat: "Caminata", act: "Caminata, 7 km/h, en llano, superficie firme, paso muy rápido"},
    {cod: "17231", met: 8.3, cat: "Caminata", act: "Caminata, 8,5 km/h, en llano, superficie firme"},
    {cod: "17235", met: 9.8, cat: "Caminata", act: "Caminata, 8,5 km/h, en ascenso, pendiente (3%)"},
    {cod: "17250", met: 3.5, cat: "Caminata", act: "Caminata, por placer, en receso de trabajo"},
    {cod: "17260", met: 4.8, cat: "Caminata", act: "Caminata, en pista de césped"},
    {cod: "17262", met: 4.5, cat: "Caminata", act: "Caminata, paso normal, en campo arado o arena"},
    {cod: "17270", met: 4.0, cat: "Caminata", act: "Caminata, al trabajo o clase (Código Taylor 015)"},
    {cod: "17280", met: 2.5, cat: "Caminata", act: "Caminata, hacia y desde una dependencia externa de la casa"},
    {cod: "17302", met: 4.8, cat: "Caminata", act: "Caminata, como ejercicio, 5,5 a 6,5 km/h, con bastones de ski, caminata Nórdica, en llano, paso moderado"},
    {cod: "17305", met: 9.5, cat: "Caminata", act: "Caminata, como ejercicio, 8 km/h, con bastones de ski, caminata Nórdica, en llano, paso rápido"},
    {cod: "17310", met: 6.8, cat: "Caminata", act: "Caminata, como ejercicio, con bastones de ski, caminata Nórdica, en ascenso"},
    {cod: "17320", met: 6.0, cat: "Caminata", act: "Caminata, hacia atrás, 5,5 km/h, en llano"},
    {cod: "17325", met: 8.0, cat: "Caminata", act: "Caminata, hacia atrás, 5,5 Km/h, en ascenso,pendiente 5"},



//ACTIVIDADES ACUATICAS

    {cod: "18010", met: 2.5, cat: "Actividades Acuáticas", act: " Navegación, a motor, conduciendo"},
    {cod: "18012", met: 1.3, cat: "Actividades Acuáticas", act: " Navegación, a motor, pasajero, ligero"},
    {cod: "18020", met: 4.0, cat: "Actividades Acuáticas", act: " Canotaje, en camping (Código Taylor 270)"},
    {cod: "18025", met: 3.3, cat: "Actividades Acuáticas", act: " Canotaje, en recolección de arroz, quite de arroz del tallo"},
    {cod: "18030", met: 7.0, cat: "Actividades Acuáticas", act: " Canotaje, transporte de canoa por tierra"},
    {cod: "18040", met: 2.8, cat: "Actividades Acuáticas", act: " Canotaje, remando, 3-6 km/h, esfuerzo ligero"},
    {cod: "18050", met: 5.8, cat: "Actividades Acuáticas", act: " Canotaje, remando, 6-9,5 km/h, esfuerzo moderado"},
    {cod: "18060", met: 12.5, cat: "Actividades Acuáticas", act: " Canotaje, remando, haciendo kayac, en competencia, >9,66 km/h, esfuerzo intenso"},
    {cod: "18070", met: 3.5, cat: "Actividades Acuáticas", act: " Canotaje, remando, por placer, general (Código Taylor 250)"},
    {cod: "18080", met: 12.0,cat: "Actividades Acuáticas", act: " Canotaje, remando, en competencia, en equipo o con bote a remos (Código Taylor 260)"},
    {cod: "18090", met: 3.0, cat: "Actividades Acuáticas", act: " Clavado, desde trampolín o plataforma"},
    {cod: "18100", met: 5.0, cat: "Actividades Acuáticas", act: "Uso de kayac, esfuerzo moderado"},
    {cod: "18110", met: 4.0, cat:" Actividades Acuáticas", act: " Bote a pedales"},
    {cod: "18120", met: 3.0, cat: "Actividades Acuáticas", act: " Navegación, en bote y embarcación, windsurf, navegación en hielo, general (Código Taylor 235)"},
    {cod: "18130", met: 4.5, cat: "Actividades Acuáticas", act: " Navegación, en competencia"},
    {cod: "18140", met: 3.3, cat: "Actividades Acuáticas", act: " Navegación, en Sunfish/Laser/Hobby Cat, barco con quilla, navegación en océano, navegación a vela, por placer"},
    {cod: "18150", met: 6.0, cat: "Actividades Acuáticas", act: " Esquí acuático o en tabla (Código Taylor 220)"},
    {cod: "18160", met: 7.0, cat: "Actividades Acuáticas", act: " Esquí en moto de agua, manejo de moto"},
    {cod: "18180", met: 15.8, cat: "Actividades Acuáticas", act: " Actividades subacuáticas, rápidas"},
    {cod: "18190", met: 11.8, cat: "Actividades Acuáticas", act: "Actividades subacuáticas, moderadas"},
    {cod: "18200", met: 7.0, cat: "Actividades Acuáticas", act: " Actividades subacuáticas, buceo, general (Código Taylor 310)"},
    {cod: "18210", met: 5.0, cat: "Actividades Acuáticas", act: "Actividades con uso de snorkel (Código Taylor 310)"},
    {cod: "18220", met: 3.0, cat: "Actividades Acuáticas", act: " Surf, con o sin tabla, general"},
    {cod: "18222", met: 5.0, cat: "Actividades Acuáticas", act: " Surf, con o sin tabla, competitivo"},
    {cod: "18225", met: 6.0, cat: "Actividades Acuáticas", act: " Remo de pie con tabla"},
    {cod: "18230", met: 9.8, cat: "Actividades Acuáticas", act: " Vueltas de natación. estilo libre, rápido, esfuerzo intenso"},
    {cod: "18240", met: 5.8, cat: "Actividades Acuáticas", act: " Vueltas de natación. estilo libre, crawl, lento, esfuerzo ligero o moderado"},
    {cod: "18250", met: 9.5, cat: "Actividades Acuáticas", act: " Natación, estilo espalda, general, entrenamiento o competición"},
    {cod: "18255", met: 4.8, cat: "Actividades Acuáticas", act: " Natación, estilo espalda, recreativo"},
    {cod: "18260", met: 10.3, cat: "Actividades Acuáticas", act: " Natación, estilo pecho, general, entrenamiento o competición"},
    {cod: "18265", met: 5.3, cat: "Actividades Acuáticas", act: " Natación, estilo pecho, recreativo"},
    {cod: "18270", met: 13.8, cat: "Actividades Acuáticas", act: " Natación, estilo mariposa, general"},
    {cod: "18280", met: 10.0, cat: "Actividades Acuáticas", act: " Natación, crawl, alta velocidad, ~69 m/min, esfuerzo intenso"},
    {cod: "18290", met: 8.3, cat: "Actividades Acuáticas", act: " Natación, crawl, velocidad media, ~46m/min, esfuerzo intenso"},
    {cod: "18300", met: 6.0, cat: "Actividades Acuáticas", act: " Natación, lago, océano, río (Código Taylor 280,295)"},
    {cod: "18310", met: 6.0, cat: "Actividades Acuáticas", act: " Natación, recreativo, sin realizar vueltas, general"},
    {cod: "18320", met: 7.0, cat: "Actividades Acuáticas", act: " Natación, nado lateral, general"},
    {cod: "18330", met: 8.0, cat: "Actividades Acuáticas", act: " Natación, nado sincronizado"},
    {cod: "18340", met: 9.8, cat: "Actividades Acuáticas", act: " Natación, flotación vertical con impulso de piés, rápido, esfuerzo intenso"},
    {cod: "18350", met: 3.5, cat: "Actividades Acuáticas", act: " Natación, flotación vertical con impulso de piés, esfuerzo moderado, general"},
    {cod: "18352", met: 2.3, cat: "Actividades Acuáticas", act: " Flotación sobre neumático en río, general"},
    {cod: "18355", met: 5.5, cat: "Actividades Acuáticas", act: " Gimnasia acuática, calistenia en el agua"},
    {cod: "18360", met: 10.0, cat: "Actividades Acuáticas", act: " Water polo"},
    {cod: "18365", met: 3.0, cat: "Actividades Acuáticas", act: " Water volley"},
    {cod: "18366", met: 9.8, cat: "Actividades Acuáticas", act: " Trote en el agua"},
    {cod: "18367", met: 2.5, cat: "Actividades Acuáticas", act: " Caminata en el agua, esfuerzo ligero, paso lento"},
    {cod: "18368", met: 4.5, cat: "Actividades Acuáticas", act: "Caminata en el agua, esfuerzo moderado, paso moderado"},
    {cod: "18369", met: 6.8, cat: "Actividades Acuáticas", act: "Caminata en el agua, esfuerzo intenso, paso rápido"},
    {cod: "18370", met: 5.0, cat: "Actividades Acuáticas", act: " Rafting, kayaking o canotaje"},
    {cod: "18380", met: 5.0, cat: "Actividades Acuáticas", act: " Windsurf, sin impulso para aumentar la velocidad"},
    {cod: "18385", met: 11.0, cat: "Actividades Acuáticas", act: " Windsurf o Kitesurf, realizando pruebas"},
    {cod: "18390", met: 13.5, cat: "Actividades Acuáticas", act: " Windsurf en competencia, con impulso para aumentar la velocidad"},
      

//ACTIVIDADES INVERNALES
    {cod: "19005", met: 7.5, cat: "Actividades Invernales", act: "Conducción de trineo tirado por perros" },
    {cod: "19006", met: 2.5, cat: "Actividades Invernales", act: "Pasajero de trineo tirado por perros" },
    {cod: "19010", met: 6.0, cat: "Actividades Invernales", act: "Mudanza de casa de hielo, montaje/perforación" },
    {cod: "19011", met: 2.0, cat: "Actividades Invernales", act: "Pesca en hielo, sentado" },
    {cod: "19018", met: 14.0, cat: "Actividades Invernales", act: "Patinaje sobre hielo, alto rendimiento" },
    {cod: "19020", met: 5.5, cat: "Actividades Invernales", act: "Patinaje sobre hielo, 14,5 km/h o menos" },
    {cod: "19030", met: 7.0, cat: "Actividades Invernales", act: "Patinaje sobre hielo, general" },
    {cod: "19040", met: 9.0, cat: "Actividades Invernales", act: "Patinaje sobre hielo, velóz, > 14,5 km/h" },
    {cod: "19050", met: 13.3, cat: "Actividades Invernales", act: "Patinaje, en velocidad, competitivo" },
    {cod: "19060", met: 7.0, cat: "Actividades Invernales", act: "Salto con esquís, ascenso transportando esquís" },
    {cod: "19075", met: 7.0, cat: "Actividades Invernales", act: "Esquí, general" },
    {cod: "19080", met: 6.8, cat: "Actividades Invernales", act: "Esquí de fondo, 4 km/h, esfuerzo ligero" },
    {cod: "19090", met: 9.0, cat: "Actividades Invernales", act: "Esquí de fondo, 6,5-8 km/h, moderado" },
    {cod: "19100", met: 12.5, cat: "Actividades Invernales", act: "Esquí de fondo, 8-12,5 km/h, esfuerzo intenso" },
    {cod: "19110", met: 15.0, cat: "Actividades Invernales", act: "Esquí de fondo, >13 km/h, elite, carrera" },
    {cod: "19130", met: 15.5, cat: "Actividades Invernales", act: "Esquí de fondo, cuesta arriba, máximo, alpinismo" },
    {cod: "19135", met: 13.3, cat: "Actividades Invernales", act: "Esquí de fondo, patinaje" },
    {cod: "19140", met: 13.5, cat: "Actividades Invernales", act: "Esquí de fondo, biatlón, técnica de patinaje" },
    {cod: "19150", met: 4.3, cat: "Actividades Invernales", act: "Esquí alpino o snowboard, esfuerzo ligero" },
    {cod: "19160", met: 5.3, cat: "Actividades Invernales", act: "Esquí alpino o snowboard, moderado, general" },
    {cod: "19170", met: 8.0, cat: "Actividades Invernales", act: "Esquí, cuesta abajo, esfuerzo intenso, carrera" },
    {cod: "19175", met: 12.5, cat: "Actividades Invernales", act: "Esquí, roller, corredores de elite" },
    {cod: "19180", met: 7.0, cat: "Actividades Invernales", act: "Deslizamiento en nieve, bobsleigh, luge" },
    {cod: "19190", met: 5.3, cat: "Actividades Invernales", act: "Snow shoeing, esfuerzo moderado" },
    {cod: "19192", met: 10.0, cat: "Actividades Invernales", act: "Snow shoeing, esfuerzo intenso" },
    {cod: "19200", met: 3.5, cat: "Actividades Invernales", act: "Conducción de moto de nieve, moderado" },
    {cod: "19202", met: 2.0, cat: "Actividades Invernales", act: "Pasajero de moto de nieve" },
    {cod: "19252", met: 5.3, cat: "Actividades Invernales", act: "Uso de pala manual en nieve, esfuerzo moderado" },
    {cod: "19254", met: 7.5, cat: "Actividades Invernales", act: "Uso de pala manual en nieve, esfuerzo intenso" },
    {cod: "19260", met: 2.5, cat: "Actividades Invernales", act: "Remoción de nieve con máquina, caminando" },


//ACTIVIDADES RELIGIOSAS

    {cod: "20000", met: 1.3, cat: "Actividades Religiosas", act: "Sentado en la iglesia, en misa, sentado silenciosamente" },
    {cod: "20001", met: 2.0, cat: "Actividades Religiosas", act: "Sentado, tocando un instrumento en la iglesia" },
    {cod: "20005", met: 1.8, cat: "Actividades Religiosas", act: "Sentado en la iglesia, conversando o cantando, participación activa" },
    {cod: "20010", met: 1.3, cat: "Actividades Religiosas", act: "Sentado, leyendo material religioso en el hogar" },
    {cod: "20015", met: 1.3, cat: "Actividades Religiosas", act: "De pie silenciosamente en la iglesia" },
    {cod: "20020", met: 2.0, cat: "Actividades Religiosas", act: "De pie, cantando en la iglesia" },
    {cod: "20025", met: 1.3, cat: "Actividades Religiosas", act: "De rodillas en la iglesia o el hogar, rezando" },
    {cod: "20030", met: 1.8, cat: "Actividades Religiosas", act: "De pie, conversando en la iglesia" },
    {cod: "20035", met: 2.0, cat: "Actividades Religiosas", act: "Caminando en la iglesia" },
    {cod: "20036", met: 2.0, cat: "Actividades Religiosas", act: "Caminando, a menos de 3 km/h, muy lento" },
    {cod: "20037", met: 3.5, cat: "Actividades Religiosas", act: "Caminando, 5 km/h, velocidad moderada, sin carga" },
    {cod: "20038", met: 4.3, cat: "Actividades Religiosas", act: "Caminando, 5,5 km/h, velozmente, sin carga" },
    {cod: "20039", met: 2.0, cat: "Actividades Religiosas", act: "Combinación de caminata y detención en funciones religiosas" },
    {cod: "20040", met: 5.0, cat: "Actividades Religiosas", act: "Alabanzas con movimientos, danzas espirituales" },
    {cod: "20045", met: 2.5, cat: "Actividades Religiosas", act: "Servir comida en la iglesia" },
    {cod: "20046", met: 2.0, cat: "Actividades Religiosas", act: "Preparación de alimentos en la iglesia" },
    {cod: "20047", met: 3.3, cat: "Actividades Religiosas", act: "Lavado de platos, limpieza de cocina en la iglesia" },
    {cod: "20050", met: 1.5, cat: "Actividades Religiosas", act: "Comer en la iglesia" },
    {cod: "20055", met: 2.0, cat: "Actividades Religiosas", act: "Comer/conversar en la iglesia o comer de pie" },
    {cod: "20060", met: 3.3, cat: "Actividades Religiosas", act: "Limpieza de la iglesia" },
    {cod: "20061", met: 4.0, cat: "Actividades Religiosas", act: "Jardinería general en la iglesia" },
    {cod: "20065", met: 3.5, cat: "Actividades Religiosas", act: "De pie, esfuerzo moderado, cargando objetos" },
    {cod: "20095", met: 4.5, cat: "Actividades Religiosas", act: "De pie, esfuerzo moderado a intenso, labores manuales, cargando ≥22,5 kg" },
    {cod: "20100", met: 1.3, cat: "Actividades Religiosas", act: "Tipeo, eléctrico, manual o en computadora" },



//ACTIVIDADES VOLUNTARIAS
    {cod: "21000", met: 1.5, cat: "Actividades Voluntarias", act: "Sentado, en reunión, general, y/o conversando" },
    {cod: "21005", met: 1.5, cat: "Actividades Voluntarias", act: "Sentado, trabajo de oficina ligero, en general" },
    {cod: "21010", met: 2.5, cat: "Actividades Voluntarias", act: "Sentado, trabajo moderado" },
    {cod: "21015", met: 2.3, cat: "Actividades Voluntarias", act: "De pie, trabajo ligero (archivando, conversando)" },
    {cod: "21016", met: 2.0, cat: "Actividades Voluntarias", act: "Sentado, cuidando niños, solo períodos activos" },
    {cod: "21017", met: 3.0, cat: "Actividades Voluntarias", act: "De pie, cuidando niños, solo períodos activos" },
    {cod: "21018", met: 3.5, cat: "Actividades Voluntarias", act: "Caminar/correr jugando con niños, moderado" },
    {cod: "21019", met: 5.8, cat: "Actividades Voluntarias", act: "Caminar/correr jugando con niños, intenso" },
    {cod: "21020", met: 3.0, cat: "Actividades Voluntarias", act: "De pie, trabajo ligero/moderado (empaque, reparación)" },
    {cod: "21025", met: 3.5, cat: "Actividades Voluntarias", act: "De pie, moderado (cargando 22,5 kg, velocidad)" },
    {cod: "21030", met: 4.5, cat: "Actividades Voluntarias", act: "De pie, trabajo moderado/pesado" },
    {cod: "21035", met: 1.3, cat: "Actividades Voluntarias", act: "Tipeo, eléctrico, manual o en computadora" },
    {cod: "21040", met: 2.0, cat: "Actividades Voluntarias", act: "Caminata, menos de 3 km/h, muy lento" },
    {cod: "21045", met: 3.5, cat: "Actividades Voluntarias", act: "Caminata, 6 km/h, moderada velocidad, sin carga" },
    {cod: "21050", met: 4.3, cat: "Actividades Voluntarias", act: "Caminata, 5,6 km/h, veloz, sin carga" },
    {cod: "21055", met: 3.5, cat: "Actividades Voluntarias", act: "Caminata, 4 km/h, lento, transportando < 11 kg" },
    {cod: "21060", met: 4.5, cat: "Actividades Voluntarias", act: "Caminata, 5 km/h, moderado, transportando < 11 kg" },
    {cod: "21065", met: 4.8, cat: "Actividades Voluntarias", act: "Caminata, 5,6 km/h, rápida, transportando < 11 kg" },
    {cod: "21070", met: 3.0, cat: "Actividades Voluntarias", act: "Combinación de caminata y detención en funciones voluntarias" }



]


